### ISSUE TITLE
Delete from existing array or set it to empty array

### ISSUE THREAD

**Issue by dcompoze** [TomWright/dasel#106]
Is it possible to remove an item from an array or set an array to an empty array?

Given a foo.toml file like so:

```
[company]
employees = ["bob", "kate", "john"]
```

I can append an item with:

    dasel put string -f foo.toml 'company.employees.[]' sarah

I can change a specific item with:

    dasel put string -f foo.toml 'company.employees.[1]' sarah

But how would I go about deleting an item from the array?
I tried omitting the value:

    dasel put string -f foo.toml 'company.employees.[1]'

But it only sets the element to an empty string.

Also how would I set an existing array to an empty array?
I tried setting it to a new object but it creates a new object instead of an array:

    dasel put object -f foo.toml 'company.employees'

And there doesn't seem to be a type of 'array' only 'object', 'string', 'int' etc.

**Comment by TomWright** [comment]
Hey @dcompoze ,

I've got a discussion open for this feature here: https://github.com/TomWright/dasel/discussions/64

There's a couple of unanswered questions (I just haven't gotten round to it yet) but I can revisit this sooner if there's a need for it.

You can use `put document` to replace a key with an empty array:
```
dasel put document -f foo.toml -d json  '.company.employees' '[]'
```

**Comment by dcompoze** [comment]
Great, this `dasel put document -f foo.toml -d json  '.company.employees' '[]'` works for me.

**Comment by TomWright** [comment]
OK great - I'll close this issue now and we can track progress on the delete feature request in the discussions section.
