### ISSUE TITLE
dasel --version shows 'development' when built from master branch

### ISSUE THREAD

**Issue by dcompoze** [TomWright/dasel#107]
Running `dasel --version` returns the following when built from GitHub:

    dasel version development

Which doesn't actually say which version it is (e.g. version number or git hash)

**Comment by TomWright** [comment]
If you build dasel yourself, no matter the source, it will have a development version.

Only the executables added against the releases on GitHub have a version, bring the related tag that triggered the release.

To confirm, you did clone the repo and build yourself right?

**Comment by dcompoze** [comment]
Yes with `go install cmd/dazel`.
Although I think it would be useful to include at least part of the git hash when building locally (e.g. development-47aa6ce) - otherwise when I create an issue I don't know which git commit I built the binary from.

**Comment by TomWright** [comment]
I've started working on an implementation to do just this, but it seems like there is a bug within the go tools that will block it for now: https://github.com/golang/go/issues/29228

**Comment by TomWright** [comment]
I've made this change and it will take effect from 6289ed13b5ea96535721d16278f23e4e4615c6ee.

E.g.

```
$ go install github.com/tomwright/dasel/cmd/dasel@master
go: downloading github.com/tomwright/dasel v1.13.6-0.20210323214150-f411354439b3
$ ~/go/bin/dasel -v
dasel version development-v1.13.6-0.20210323214150-f411354439b3
```

This will work when specifying a full package name, but when installing from a local source as you did before may still show `development` due to the issue I linked above.
