### ISSUE TITLE
Expose this as a library

### ISSUE THREAD

**Issue by alexkreidler** [TomWright/dasel#112]
This is a great project. I found myself itching to use it in a Go project that requests various data (JSON, XML, CSV) from web sources, but was hesitant at the thought of writing temporary files and piping to `dasel`s stdin.

I know that maintaining libraries can be more involved, especially regarding with versioning, API stability etc. Nevertheless, with a cursory glance at the code, it seems the readers and writers all just take and return byte slices, so it doesn't seem like it'd be too difficult to open up. I could envision this being quite useful for others. 

Of course, it's your call. Thanks again!

**Comment by TomWright** [comment]
Hey @alexkreidler, thanks for the feedback!

You can use dasel to a large extent already. There's some basic documentation here: https://github.com/TomWright/dasel#using-dasel-as-a-go-package

I can add more docs or expose more functionality if you need it.

I'm on my phone at the moment but if you let me know what you're trying to do I can put together an example when I'm at the computer 🙂

**Comment by alexkreidler** [comment]
Ah, silly mistake! I overlooked that section. Yeah that should be great, thanks.

**Comment by TomWright** [comment]
No worries!

**Comment by beatcracker** [comment]
> There's some basic documentation here: https://github.com/TomWright/dasel#using-dasel-as-a-go-package

The correct link now is https://daseldocs.tomwright.me/use-as-a-go-package
