### ISSUE TITLE
Add install instructions in readme

### ISSUE THREAD

**Issue by matthiasdebernardini** [TomWright/dasel#122]
title basically, cant find this information at a glance.

looks nice!

**Comment by TomWright** [comment]
Fair point - I recently moved all the documentation over to gitbook and the installation instructions went with it.

I'll update the readme with some basic instructions 👍

**Comment by matthiasdebernardini** [comment]
I couldn't find that when I clicked on the links but yea top three or five most popular ways to install it would be cool

**Comment by TomWright** [comment]
For reference the install directions are here: https://daseldocs.tomwright.me/installation

**Comment by TomWright** [comment]
I've added a quickstart section to the readme now: https://github.com/TomWright/dasel#quickstart

I think that's sufficient - would you agree?

**Comment by matthiasdebernardini** [comment]
I would. Cheers!
