### ISSUE TITLE
aarch64 release binary

### ISSUE THREAD

**Issue by paradajz** [TomWright/dasel#125]
**Is your feature request related to a problem? Please describe.**
Yes.

**Describe the solution you'd like**
Provide aarch64 binary in releases so that manual compilation of dasel on aarch64 (eg. Raspberry Pi) isn't needed.

**Describe alternatives you've considered**
I've tried to manually compile dasel on Raspberry Pi. dasel works as expected. Additionally, I've run your test suite although I'm not sure if I needed to run anything before this:

```
ubuntu@ubuntu:~/dev/git/dasel$ go test -coverprofile=coverage.txt -covermode=atomic -race ./...
ok  	github.com/tomwright/dasel	1.976s	coverage: 93.7% of statements
?   	github.com/tomwright/dasel/cmd/dasel	[no test files]
?   	github.com/tomwright/dasel/internal	[no test files]
ok  	github.com/tomwright/dasel/internal/command	0.657s	coverage: 93.1% of statements
ok  	github.com/tomwright/dasel/internal/oflag	0.044s	coverage: 100.0% of statements
?   	github.com/tomwright/dasel/internal/selfupdate	[no test files]
ok  	github.com/tomwright/dasel/internal/storage	0.104s	coverage: 88.6% of statements

```

**Comment by TomWright** [comment]
I'll update the build actions and tag a new release soon 👍

**Comment by TomWright** [comment]
Here we go: https://github.com/TomWright/dasel/releases/tag/v1.14.1

It's the arm64 binary 🙂

**Comment by paradajz** [comment]
Thank you!
