### ISSUE TITLE
Json Lines

### ISSUE THREAD

**Issue by FandaOG** [TomWright/dasel#134]
Hi,

could you support *.jsonl files? https://jsonlines.org/

Thanks.

**Comment by TomWright** [comment]
Hey @FandaOG,

Thanks for your interest in dasel.

I believe this should already work.

From https://jsonlines.org/examples:

```bash
echo '["Name", "Session", "Score", "Completed"]
["Gilbert", "2013", 24, true]
["Alexa", "2013", 29, true]
["May", "2012B", 14, false]
["Deloise", "2012A", 19, true] ' | dasel -p json .
```
```json
[
  "Name",
  "Session",
  "Score",
  "Completed"
]
[
  "Gilbert",
  "2013",
  24,
  true
]
[
  "Alexa",
  "2013",
  29,
  true
]
[
  "May",
  "2012B",
  14,
  false
]
[
  "Deloise",
  "2012A",
  19,
  true
]
```

The only change you may desire is that `.jsonl` files get automatically detected as JSON content, but for the time being you can either store your data in a `.json` file or pass `-p json` to dasel to tell it which parser to use.

**Comment by FandaOG** [comment]
Thank you @TomWright. I tried bad selector. It works perfect.

![image](https://user-images.githubusercontent.com/61017336/117296759-bbcb4680-ae75-11eb-8384-06b10f2d3af2.png)
