### ISSUE TITLE
Colored output like jq or yq

### ISSUE THREAD

**Issue by kadamanas93** [TomWright/dasel#136]
Right now, dasel output is plain terminal color and it would be nice for readability for dasel to support colored text.

Currently I am piping the output of dasel to yq or jq depending on the document syntax like so:

`echo '{"name":"Tom"}' | dasel -p json | jq`

**Comment by TomWright** [comment]
I can see the value in this.

The interesting thing is that I'd need something to parse and colourise all of the data formats

**Comment by TomWright** [comment]
Looking into options for this.

https://github.com/alecthomas/chroma looks promising.

Output could be colourised with a `--color` or `--colour`.

**Comment by TomWright** [comment]
From `v1.19.0` you can colourise the output from select commands by adding the `--colour` or `--color` flag.

![image](https://user-images.githubusercontent.com/935867/129446992-5f3c0c06-d1c7-4d3c-8b64-08e20b28c5fb.png)

**Comment by dalegaspi** [comment]
nit: the command only recognized `--colour` but not `--color`
