### ISSUE TITLE
Consider adding data-processing, data-wrangling to your github tags.

### ISSUE THREAD

**Issue by emilebosch** [TomWright/dasel#152]
**Is your feature request related to a problem? Please describe.**
I couldn't find your repo. Pain ensued.

**Describe the solution you'd like**
Found your repo.  Joy ensued.

**Describe alternatives you've considered**
Hacking all things sed, ack, jq, csvkit, yaml2csv etc. 

**Additional context**
Keep up the good work!

**Comment by TomWright** [comment]
Thanks for the suggestion. I've added those now! 👍
