### ISSUE TITLE
Print json output for multi-document YAML

### ISSUE THREAD

**Issue by ryuheechul** [TomWright/dasel#153]
**Describe the bug**
Multi-doc YAML not being printed.

I can see that multi-doc YAML work with YAML output thanks to https://github.com/TomWright/dasel/issues/29

**To Reproduce**
1. Run simple scripts like below

```bash
$ cat <<EOF | dasel -f /dev/stdin -p yaml
---
document: 1
---
document: 2
---
document: 3
EOF
document: 1
---
document: 2
---
document: 3


$ cat <<EOF | dasel -f /dev/stdin -p json
---
document: 1
---
document: 2
---
document: 3
EOF
Error: could not load input: could not unmarshal data: invalid character '-' in numeric literal


$ cat <<EOF > example.yaml
---
document: 1
---
document: 2
---
document: 3
EOF

$ dasel -f example.yaml -p json
Error: could not load input: could not unmarshal data: invalid character '-' in numeric literal
```

Include (sanitized) input files and commands to help along the way.
```yaml
---
document: 1
---
document: 2
---
document: 3
```

**Expected behavior**

similar results like [yq](https://github.com/kislyuk/yq/tree/c095bd515214139a8f6dbc5d495393241092ce3f) 
```
$ cat example.yaml | yq
{
  "document": 1
}
{
  "document": 2
}
{
  "document": 3
}
```

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS
 - Version: 1.17.0

**Comment by TomWright** [comment]
Hey @ryuheechul,

I believe this is a misunderstanding of how to use certain flags with dasel.

See the following that works:

Read from file, output to JSON.
```
$ dasel -f example.yaml -w json
{
  "document": 1
}
{
  "document": 2
}
{
  "document": 3
}
```

Read from stdin. Read parser is YAML, write parser is JSON.
```
$ cat example.yaml | dasel -r yaml -w json
{
  "document": 1
}
{
  "document": 2
}
{
  "document": 3
}
```

Read from stdin using EOF. Read parser is YAML, writer parser is JSON.
```
$ cat <<EOF | dasel -r yaml -w json
---
document: 1
---
document: 2
---
document: 3
EOF
{
  "document": 1
}
{
  "document": 2
}
{
  "document": 3
}
```

Read specifically from stdin using EOF. Read parser is YAML, writer parser is JSON.
```
$ cat <<EOF | dasel -f stdin -r yaml -w json
---
document: 1
---
document: 2
---
document: 3
EOF
{
  "document": 1
}
{
  "document": 2
}
{
  "document": 3
}
```

For more information please see the [select docs](https://daseldocs.tomwright.me/usage/select#flags), specifically those regarding the following flags:
- `-f`,`--file`
- `-r`,`--read`
- `-w`,`--write`
- `-p`,`--parser`

I believe this should solve your problem 👍

**Comment by ryuheechul** [comment]
Hey @TomWright,
Thank you very much for your answer.
It's my bad of misunderstanding about what `-p` was.
Somehow I automatically thought it was for "print" by looking at examples in [README.md](https://github.com/TomWright/dasel/blob/1facf4ea07d8acb9b1a150c144fb734691e6c1aa/README.md) 😅 .

You perfectly educated me on this and thanks for the clarification 👍🏼.
