### ISSUE TITLE
Module name: match case?

### ISSUE THREAD

**Issue by herbygillot** [TomWright/dasel#157]
Would it make sense for `dasel`'s Go module to match the case of the repository?

ie., `github.com/TomWright/dasel` instead of `github.com/tomwright/dasel`

**Comment by TomWright** [comment]
I do agree with you but have concerns about the backward compatibility of this change.

**Comment by TomWright** [comment]
Thinking about it, this would be a breaking change regardless of when it's made. I'm open to making the change but this is also the first time it's come up as an issue.

Perhaps I could get some feedback on this issue so I can see what kind of impact it will have.

- Are you using dasel as a go import?
- Are you referencing the go module from some external place? If so, where?

If I'm going to change the package name, I may well change it to a vanity URL: `go.tomwright.me/dasel`.
This will protect against these issues in the future.

**Comment by TomWright** [comment]
Closing this as a non-issue right now. Tackling this will cause backwards incompatibility issues.
