### ISSUE TITLE
Selectors with non US standard characters not working in dynamic selectors

### ISSUE THREAD

**Issue by reynn** [TomWright/dasel#159]
**Describe the bug**

I have a small subset of json for a game called Azur Lane, which contains various information about the characters. One of the characters is named `Ägir` which I have not been able to find a way to do a dynamic selector on.

**To Reproduce**

1. Create json with the following content at `/tmp/al.json
   ```json
    {
      "data": [
        {"name": "Fu Shun", "ship_type": "Destroyer"},
        {"name": "Sheffield", "ship_type": "Light Cruiser"},
        {"name": "Ägir", "ship_type": "Large Cruiser"}
      ]
    }
   ```
2. Try one of the following selectors:
    1. `dasel select -f /tmp/tmp.json --plain -s '.data.(name=Ägir).ship_type'`
    2. `dasel select -f /tmp/tmp.json --plain -s '.data.(name=\Ägir).ship_type'`
4. See error `Error: could not query node: could not find value: no value found for selector: ).ship_type:`

**Expected behavior**
output for these selectors should be `Large Cruiser`

**Desktop (please complete the following information):**
 - OS: OS X 11.5.2
 - Version: v1.19.0

**Additional Context**
I tried to quote the name as well but that doesn't seem to be supported. Unclear if Go issue for some reason or just a small issue with the selector logic.

**Comment by TomWright** [comment]
The problem has been fixed here: https://github.com/TomWright/dasel/pull/160

I'll merge this and release shortly under `v1.19.1`.
