### ISSUE TITLE
Unable to parse ISO-8859-1 XML

### ISSUE THREAD

**Issue by cgardner** [TomWright/dasel#164]
**Describe the bug**
I'm not able to use dasel to parse an XML file that is ISO-8859-1 encoded.

**To Reproduce**

1. Create a file with the example XML from below
2. Execute `dasel -f /path/to/example.xml -p xml`
3. The command will fail with the following message:
    > Error: could not load input: could not unmarshal data: xml.Decoder.Token() - xml: encoding "ISO-8859-1" declared but Decoder.CharsetReader is nil

```xml
<!-- example.xml -->
<?xml version="1.0" encoding="ISO-8859-1"?>
<response>
</response>
```

**Expected behavior**
I would expect to be able to use dasel with these files

**Desktop (please complete the following information):**
 - OS: MacOS 10.15.7
 - Version: 1.20.0

**Comment by TomWright** [comment]
Hi @cgardner,

I'm away from home for a couple of days but will check this out when I'm back

**Comment by brenol** [comment]
Hit this myself when using dasel Go's API directly, and found a simple fix inside mxj :) Opened a PR, hope it helps!

**Comment by TomWright** [comment]
Thanks to @brenol - this was fixed in https://github.com/TomWright/dasel/pull/165

I'll release this shortly under `v1.20.1`.

**Comment by TomWright** [comment]
This issue is now solved.

```
$ cat test.xml
<!-- example.xml -->
<?xml version="1.0" encoding="ISO-8859-1"?>
<response>
</response>

$ dasel -v
dasel version v1.20.1

$ dasel -f test.xml .
<response/>
```

**Comment by cgardner** [comment]
That worked!  Thank you!
