### ISSUE TITLE
dasel should write error messages to stderr rather than stdout

### ISSUE THREAD

**Issue by TamasSzerb** [TomWright/dasel#174]
**Describe the bug**
dasel always writes to stdout, even error messages so difficult to process its output

**To Reproduce**
echo '<xml><test>moo</test></xml>' | dasel -p xml -m
 '.xml.NOtest' 2>/dev/null
Error: could not query multiple node: could not find multiple value: no value found for selector: .NOtest: map[test:moo]
Include (sanitized) input files and commands to help along the way.

while the non-errorous:

echo '<xml><test>moo</test></xml>' | dasel -p xml -m '.xml.test' 2>/dev/null
moo

**Expected behavior**
The error messages should go to stderr rather than stdout

**Desktop (please complete the following information):**
 - Ubuntu 20.04.3 LTS
 - dasel version v1.21.1

**Comment by TomWright** [comment]
This is merged and will be released in the next version.

**Comment by TomWright** [comment]
This is released and fixed as of `v1.22.0`.
