### ISSUE TITLE
Is there some sort of mechanism blocking release downloads?

### ISSUE THREAD

**Issue by ypicard** [TomWright/dasel#179]
I have a CI script which installs `dasel` the following way:
```
curl -s https://api.github.com/repos/tomwright/dasel/releases/latest | grep browser_download_url | grep linux_amd64 | cut -d '"' -f 4 | wget -qi - && mv dasel_linux_amd64 dasel && chmod +x dasel && mv ./dasel /usr/local/bin/dasel
```

Every now and then, this snippet will return the following:
```
mv: cannot stat 'dasel_linux_amd64': No such file or directory
```

Re-triggering it a minute later will solve the problem.

This behavior is cryptic to me. Is there some sort of mechanism that would block downloads in specific situations? Any clue on why this might happen, if not related to this project? This is the only binary I have this error on.

Thanks

**Comment by TomWright** [comment]
I'm aware of only 1 time when this can happen and that is when a new release is being created.

Tagging a new release triggers a pipeline that builds and adds the executables to the release. If you manage to run that script in those couple of minutes when there is no executable added on the release yet then you'll see that error.
