### ISSUE TITLE
How to match a string in a list?

### ISSUE THREAD

**Issue by rhtenhove** [TomWright/dasel#181]
With a case similar as shown in #171, I'd like to be able to find if a string is in a list.

For example:

```json
[
  "README.md",
  "tbump.toml"
]
```

I'm not sure how I'd approach this. The search selector seems to always require a key:value pair. I would for example do this using `jq`s `index`.

```shell
cat above.json | dasel -r json '.(?:whatshouldgohere=README.md)
```

**Comment by TomWright** [comment]
As per the docs: https://daseldocs.tomwright.me/selectors/dynamic#key
You can use `.` or `value` as the search key to check against the current nodes value.

```
$ echo '[
  "README.md",
  "tbump.toml"
]' | dasel -r json '.(.=README.md)'    
"README.md"
```
