### ISSUE TITLE
Add standard functions to format templates

### ISSUE THREAD

**Issue by kpym** [TomWright/dasel#188]
**Is your feature request related to a problem? Please describe.**
If I need to make a field uppercase in a template like `{{ .Name | upper }}` I can't do this with `dasel` because the of the lack of standard template functions.

**Describe the solution you'd like**
Include all functions from [sprig](https://github.com/Masterminds/sprig) for example looks like a possible solution.

**Comment by TomWright** [comment]
This is definitely an option. I'll take a look at sprig and see if I can include it in the next release.

**Comment by TomWright** [comment]
I've added this in https://github.com/TomWright/dasel/commit/b779b8820ed2b3f4c2d1adb5c0f299dccb785868 and it will be included in the next release.

**Comment by kpym** [comment]
@TomWright thanks for considering this request. May you could document this now in [Format](https://daseldocs.tomwright.me/usage/flags/format) ?

**Comment by TomWright** [comment]
I will do once I prepare the release
