### ISSUE TITLE
Question about adding values

### ISSUE THREAD

**Issue by ws-prive** [TomWright/dasel#189]
Hi @TomWright,

I am trying to read the values from https://raw.githubusercontent.com/FairwindsOps/charts/master/stable/vpa/values.yaml, read the supplied values at .recommender.extraArgs and add the lines below to .recommender.extraArgs:

```
    prometheus-address: |
      http://prometheus-operator-prometheus.prometheus-operator.svc.cluster.local:9090
    storage: prometheus
```

Is this possible?

**Comment by TomWright** [comment]
You should be able to pipe multiple dasel commands together to achieve this:

```bash
dasel put string -r values.yaml -w - .recommender.extraArgs.storage prometheus | dasel put string -r - -w values.yaml .recommender.extraArgs.prometheus-address [prometheus](http://prometheus-operator-prometheus.prometheus-operator.svc.cluster.local:9090)
```

Note that the first command reads from the file and writes to stdout, while the piped command reads from stdin and writes to the file.
