### ISSUE TITLE
Include a man page

### ISSUE THREAD

**Issue by Mrfiregem** [TomWright/dasel#201]
**Is your feature request related to a problem? Please describe.**

Having to load a web browser when wanting to view documentation is a pain and may not be possible in all situations. Having a `man` page would be useful when wishing to refresh your knowledge offline.

**Describe the solution you'd like**

A manpage that can be generated during compile time using something like `scdoc`, or included in the repo that packagers can add to their distros. Having it be written using scdoc would allow contributors to easily edit the document as well without having to learn the complex markup of roff documents.

**Comment by guilherme-puida** [comment]
I'm working on the Debian package for dasel and this is currently a pain point for me. I'm willing to write the man page(s), just wanted to check beforehand if there is already some work done :^)

**Comment by TomWright** [comment]
I haven't done any work on the man page, however dasel uses cobra and it may have some facility to help.

**Comment by guilherme-puida** [comment]
> I haven't done any work on the man page, however dasel uses cobra and it may have some facility to help.

[Nice](https://github.com/spf13/cobra/blob/main/site/content/docgen/man.md)! Didn't know about that.

I'll draft up a pull request in the next few days. Would you be OK with a new subcommand to generate the manpage (similar to the `completion` subcommand)?

**Comment by TomWright** [comment]
Yes of course! That would be great, thank you.

You'll also need to update some logic that is used to find the default command, similar to https://github.com/TomWright/dasel/commit/fed849667e23db6092b06df1cb52e3a415495eb6

**Comment by TomWright** [comment]
This change is now available in main and will be included in the next release. Install the development version to get instant access.

Thanks for the contribution @guilherme-puida !

**Comment by guilherme-puida** [comment]
Thanks! I'll let you know when the package is uploaded to the Debian archive :^)
