### ISSUE TITLE
Errors when filtering valid data from PagerDuty incidents.csv

### ISSUE THREAD

**Issue by danielhoherd** [TomWright/dasel#206]
**Describe the bug**

When attempting to filter data from the pagerduty incidents.csv, an error is thrown: `Error: could not query node: could not find value: selector [type:PROPERTY selector:.acknowledge_count] does not support value: [kind:slice type:[]map[string]interface {}] [map[acknowledge_count:1 acknowledged_by_user_ids...`

**To Reproduce**

1. Download a PagerDuty incidents.csv file (EG: from `https://your-company-name.pagerduty.com/api/v1/reports/raw/incidents.csv?since=2022-03-04T00:00:00&until=2022-03-11T16:44:25&time_zone=America/Los_Angeles`)
2. Run `dasel -r csv -w json .acknowledge_count < incidents.csv`
3. See error

<details>
<summary>Click to expand sample data</summary>

```csv
id,incident_number,description,service_id,service_name,escalation_policy_id,escalation_policy_name,created_on,resolved_on,seconds_to_first_ack,seconds_to_resolve,auto_resolved,escalation_count,auto_escalation_count,acknowledge_count,assignment_count,acknowledged_by_user_ids,acknowledged_by_user_names,assigned_to_user_ids,assigned_to_user_names,resolved_by_user_id,resolved_by_user_name,urgency
REDACTED id,1685,REDACTED description,REDACTED service id,REDACTED service name,READACTED escalation policy,REDACTED escalation policy,2022-03-08T02:04:02-08:00,2022-03-08T02:09:02-08:00,18,300,0,0,0,1,1,REDACTED user id,REDACTED user name,REDACTED user id,REDACTED user name,,,high
REDACTED id,1687,REDACTED description,REDACTED service id,REDACTED service name,READACTED escalation policy,REDACTED escalation policy,2022-03-08T02:15:32-08:00,,19,,0,0,0,3,1,REDACTED user id,REDACTED user name,REDACTED user id,REDACTED user name,,,high
REDACTED id,1704,REDACTED description,REDACTED service id,REDACTED service name,READACTED escalation policy,REDACTED escalation policy,2022-03-10T18:56:32-08:00,2022-03-10T19:01:37-08:00,17,305,0,0,0,1,1,REDACTED user id,REDACTED user name,REDACTED user id,REDACTED user name,,,high
REDACTED id,1705,REDACTED description,REDACTED service id,REDACTED service name,READACTED escalation policy,REDACTED escalation policy,2022-03-10T20:43:03-08:00,2022-03-10T20:48:02-08:00,19,299,0,0,0,1,1,REDACTED user id,REDACTED user name,REDACTED user id,REDACTED user name,,,high
```

</details>

**Expected behavior**

I expect filtering to work as described in [the jq to dasel doc](https://daseldocs.tomwright.me/examples/jq-to-dasel).

**Screenshots**

![Screen Shot 2022-03-11 at 5 16 48 PM](https://user-images.githubusercontent.com/1323808/157997693-c6357938-93bd-4d04-8fdb-3525d86cc797.png)

**Desktop (please complete the following information):**
 - OS: macOS 12.2.1 21D62 arm64, Ubuntu 21.10 x86_64
 - Version: dasel version v1.23.0

**Comment by TomWright** [comment]
The CSV data is essentially an array of records, so your selector should be the following:
```
dasel -r csv -w json -m .[*].acknowledge_count < incidents.csv
```

Here's a runnable example: https://dasel.tomwright.me/s/ee807ed2-b5eb-4dbc-a086-6a286435a545

**Comment by danielhoherd** [comment]
@TomWright Thanks for the response! I have one more question related to where I ran into this error: does dasel do variable interpolation? The full example I was doing is:

```
cat incidents.csv |
dasel -r csv -w json |
jq -r '"\(.created_on) https://company-name.pagerduty.com/incidents/\(.id) \(.description)"'
```

Which creates something like:

```
2022-03-08T02:04:02-08:00 https://company-name.pagerduty.com/incidents/REDACTED id REDACTED description
2022-03-08T02:15:32-08:00 https://company-name.pagerduty.com/incidents/REDACTED id REDACTED description
2022-03-10T18:56:32-08:00 https://company-name.pagerduty.com/incidents/REDACTED id REDACTED description
2022-03-10T20:43:03-08:00 https://company-name.pagerduty.com/incidents/REDACTED id REDACTED description
```

I couldn't find any string interpolation examples in the docs so I assume I still need jq for this. Is that correct?

**Comment by danielhoherd** [comment]
Nice! Thanks!
