### ISSUE TITLE
How to handle a yaml file with multiple kubernetes entries?

### ISSUE THREAD

**Issue by ws-prive** [TomWright/dasel#207]
Hi,

We want to add an entry to the nodeSelector field on line 5252 in our local copy of: https://github.com/kedacore/keda/releases/download/v2.6.1/keda-2.6.1.yaml

It looks like:
```
      nodeSelector:
        kubernetes.io/os: linux
```

The line we want to add below the nodeselector is: agentpool: systempool. It should look like

```
      nodeSelector:
        agentpool: systempool
        kubernetes.io/os: linux
``` 

Because the nodeSelector field is occuring multiple times, I wonder if this is possible just to add it to this occurence in the deployment of the keda-operator.

Thanks!

**Comment by ws-prive** [comment]
Thanks @TomWright, however, your example is not working. The given yaml file contains multiple yaml documents and it looks like Dasel is unable to process that correctly. When I split the documents in multiple yaml files, it is working. Is there any plan to support multiple yaml documents in one file?

**Comment by TomWright** [comment]
The file format was unclear from your question.

So you only need to add this field for the `keda-operator` deployment?

That would look like this:

```
cat keda-2.6.1.yaml | dasel put string -p yaml -m '.(.metadata.labels.app=keda-operator).spec.template.spec.nodeSelector.agentpool' 'systempool' > updated.yaml
```

**Comment by ws-prive** [comment]
This is working great, thanks!
