### ISSUE TITLE
Compact xml output

### ISSUE THREAD

**Issue by danielhoherd** [TomWright/dasel#213]
## Is your feature request related to a problem? Please describe

I would love to see compact xml output. I see that compact `-c` works with json and others

## Describe the solution you'd like

Removed line breaks and whitespace.

## Describe alternatives you've considered

`gsed -E 's/^\s+//' test.xml | tr -d '\n'`

**Comment by TomWright** [comment]
This seems reasonable. I'll do some digging into the XML parser used and see if something is easily achievable.

**Comment by TomWright** [comment]
Sorry for the slow work here, I've been busy!

This is fixed in `v1.27.3`.

**Comment by danielhoherd** [comment]
Works great! Thanks!
