### ISSUE TITLE
dasel completion is not working as expected (or I'm holding it wrong)

### ISSUE THREAD

**Issue by ismail** [TomWright/dasel#216]
```
❯ dasel --version
dasel version 1.24.3

❯ dasel 2>&1 | grep -B4 completion
Usage:
  dasel [command]

Available Commands:
  completion  generate the autocompletion script for the specified shell
```

Trying to generate completion file for fish shell:

```
❯ dasel completion fish
Error: read parser flag required when reading from stdin
```

Not sure what's that about, let's try help:

```
❯ dasel completion --help
Select properties from the given file.

Usage:
  dasel select -f <file> -p <json,yaml> -s <selector> [flags]

[...]
```
So, somehow it's aliasing to `select` sub-command.

**Comment by TomWright** [comment]
The alias of the `select` sub-command is actually intended: https://github.com/TomWright/dasel/commit/a227bd7be59d5c7c656ba48a9b0a7e3a142ba768

To be honest I didn't even know the `completion` command existed. This looks like some kind of issue here: https://github.com/TomWright/dasel/blob/74ed1bdbd5b69d663b0a07f883ee8eeaba5b4e78/internal/command/root.go#L41-L46

In that the code doesn't know that `completion` is a valid command. I'll have to do some digging here to find out what cobra is doing.

**Comment by TomWright** [comment]
I have fixed this issue here: https://github.com/TomWright/dasel/commit/fed849667e23db6092b06df1cb52e3a415495eb6
It will be included in the next release.

To use it immediately you can `go install github.com/tomwright/dasel/cmd/dasel@master`
