### ISSUE TITLE
Dasel manual install instructions broken due to amd64 gunzip release

### ISSUE THREAD

**Issue by Voxelot** [TomWright/dasel#217]
**Describe the bug**
The manual install instructions in the documentation no longer work, due to multiple releases matching the greps.

**To Reproduce**
1. Go to ['manual installation'](https://daseldocs.tomwright.me/installation#manual)
2. Run `curl -sSLf https://api.github.com/repos/tomwright/dasel/releases/latest | grep browser_download_url | grep linux_amd64 | cut -d\" -f 4`
3. See multiple conflicting artifacts returned

```
https://github.com/TomWright/dasel/releases/download/v1.24.3/dasel_linux_amd64
https://github.com/TomWright/dasel/releases/download/v1.24.3/dasel_linux_amd64.gz
```

**Expected behavior**
Should only return the first URL of the executable unzipped binary:
`https://github.com/TomWright/dasel/releases/download/v1.24.3/dasel_linux_amd64`

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04

**Comment by TomWright** [comment]
This should be ```curl -sSLf https://api.github.com/repos/tomwright/dasel/releases/latest | grep browser_download_url | grep linux_amd64 | grep -v .gz | cut -d\" -f 4```. I'll update the docs shortly
