### ISSUE TITLE
نامی

### ISSUE THREAD

**Issue by namicoin** [TomWright/dasel#218]
**Discussion?**
If this is a question rather than a bug, please raise it in the discussions Q&A section.

**Describe the bug**

**To Reproduce**

Include (sanitized) input files and commands to help along the way.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Version [e.g. 22] (`dasel --version`)

**Additional context**

**Comment by TomWright** [comment]
There's not any information here at all - please provide a description of a bug you've encountered.
