### ISSUE TITLE
Support handling of Struct types

### ISSUE THREAD

**Issue by ilaif** [TomWright/dasel#223]
First of all, thank you for this awesome OSS @TomWright 

---

### Is your feature request related to a problem? Please describe.

I have the use case of using a package like Dasel programmatically to manipulate runtime objects.

Without going into specific examples, runtime objects does not only have Slices and Maps, but also Structs.

---

### Describe the solution you'd like

I'd like Dasel to also support Structs (that are very similar functionally to Maps) when doing operations.

I've already made some local changes to dasel and it seems to work just fine. An example:

If we add the following `else if` to `findValueProperty` (https://github.com/TomWright/dasel/blob/master/node_query.go#L66):

```go
if value.Kind() == reflect.Map {
	...
} else if value.Kind() == reflect.Struct {
	fieldV := value.FieldByName(n.Selector.Property)
	  
	if fieldV.IsValid() {
		return fieldV, nil
	}
	return nilValue(), &ValueNotFound{Selector: n.Selector.Current, PreviousValue: n.Previous.Value}
}
```

Then query is able to operate on `interface{}` that contain Structs.

---

### Describe alternatives you've considered

I have an alternative private package that does similar functions to Dasel, and I'm in the ideation phase of open-sourcing it, and I would have liked to base it on Dasel, the only thing that stops me doing so ATM is the support for Structs.

---

As a last note, I'll be happy to help in integrating such a change into Dasel and would like your opinion.

Thanks!

**Comment by TomWright** [comment]
I'm open to this suggestion, in-fact I think it's a good idea.

I've been busy recently but I'll get working on it asap. If you want to raise a PR I'd also be very happy to accept one!

**Comment by TomWright** [comment]
As a note, I've also been considering adding a custom interface to wrap the `reflect.Value`. The idea here is that I can support a bunch of different types without having confusing funcs like the one you referenced, but it also may add the ability for me to add support for ordered maps.

**Comment by ilaif** [comment]
Here's a PR on a fork I've made that currently passes all of the existing unit tests (I basically replaced an internal recursive walker with dasel and it worked out of the box): https://github.com/ilaif/dasel/pull/1

What I didn't have time to dive into is why I can't change your `unwrapValue` function to also deref pointers (it messes up with the propagation logic), so for now I've added it explicitly for structs: https://github.com/ilaif/dasel/pull/1/files#diff-1eca2d2c81cf45ddcbd000468bbb54bc53101fe06fa172733c537a506b3485d8R52

**Comment by TomWright** [comment]
Thanks for raising your PR - I have a PR in draft that was facing the same issue with the `unwrapValue` but haven't had a chance to get back to it yet. I'm hoping I can find the time tomorrow to jump back in and finish it off

**Comment by TomWright** [comment]
Hey @ilaif, I've got a PR open here: https://github.com/TomWright/dasel/pull/224/files

I'd be happy if you could give it a review for me.

I used your PR as inspiration but there ended up being a few more places support was needed.

**Comment by TomWright** [comment]
Hey @ilaif,

The related PR has been merged and this will be included in the next release.

You can go get `github.com/tomwright/dasel@master` to use this functionality now.

**Comment by TomWright** [comment]
The docs have been updated: https://daseldocs.tomwright.me/use-as-a-go-package

**Comment by ilaif** [comment]
Thanks so much @TomWright! Sorry for not getting to review the PR. I'll give it a try and lyk 🙏🏽
