### ISSUE TITLE
Build for Apple M1 - Darwin ARM

### ISSUE THREAD

**Issue by ThorbenJ** [TomWright/dasel#225]
**Is your feature request related to a problem? Please describe.**
Please could you provide an Apple M1 build in dasel's releases. I could not see any darwin_arm build.

**Describe the solution you'd like**
Build for Apple M1 - MacOS on ARM (Darwin_ARM)

**Comment by TomWright** [comment]
Thanks to @reynn for his contribution here. New releases will include a darwin/arm64 release executable and a `-alpine` docker image.
