### ISSUE TITLE
Support arrays of strings

### ISSUE THREAD

**Issue by Tuditi** [TomWright/dasel#233]
**Is your feature request related to a problem? Please describe.**

I couldn't find a way to introduce an array of strings as a value for a selector.

**Describe the solution you'd like**

Running the following command:

`dasel put string[] -f Cargo.toml '.dependencies.iota-wallet.features.[]' ["mnemonic", "events"]`

would result in the following Cargo.toml file:

```
[dependencies]
  [dependencies.iota-wallet]
    features = ["mnemonic", "events"]
```

**Describe alternatives you've considered**

Other alternatives could be:

`dasel put array -f Cargo.toml '.dependencies.iota-wallet.features.[]' ["mnemonic", "events"]`

**Additional context**

Potentially this could be extended to bool/int. It's possible that a solution for this problem already exists, but then it would be nice to have an example on this in the documentation

**Comment by TomWright** [comment]
You can use `put document` for this.

https://dasel.tomwright.me/s/d2df349c-3761-4a05-9aeb-6768c860846d

```shell
$ echo '' | dasel put document -r toml -d json '.dependencies.iota-wallet.features' '["mnemonic", "events"]'

[dependencies]

  [dependencies.iota-wallet]
    features = ["mnemonic", "events"]
```
