### ISSUE TITLE
csv output converts to scientific notation

### ISSUE THREAD

**Issue by hampa** [TomWright/dasel#245]
$ echo '{"name": 10000000000.1}' | dasel -r json -w csv
name
1.00000000001e+10

Converting the output numbers to scientific notation makes it difficult to use. Can't it just print the values like they come in.

**Comment by TomWright** [comment]
It'll be the specific CSV formatter that performs this action.

A quick fix would be to use the [format](https://daseldocs.tomwright.me/usage/flags/format) flag to control the output.

Similar issue to https://github.com/TomWright/dasel/issues/229

**Comment by TomWright** [comment]
This is fixed in `v1.27.2`

```dasel
~/repos/github.com/TomWright/dasel [master] $ dasel -v
dasel version development-v1.27.2
~/repos/github.com/TomWright/dasel [master] $ echo '{"name": 10000000000.1}' | dasel -r json -w csv
name
10000000000.100000
```

**Comment by hampa** [comment]
It is not working for arrays.

echo '{ "point": [ 357809, 6394093 ] }' | dasel -r json -w csv
point
[357809 6.394093e+06]

**Comment by TomWright** [comment]
This is fixed in the latest development version:
```
$ echo '{ "point": [ 357809, 6394093 ] }' | dasel -r json -w csv
point
[357809 6394093]
```

It will be included in the next release.
