### ISSUE TITLE
yaml multiline string output contains style indicator

### ISSUE THREAD

**Issue by alexeldeib** [TomWright/dasel#253]
first, thanks for dasel! very slick and intuitive querying.

**Describe the bug**
When outputting a selected yaml field which is a multi-line string, style indicators such as `|-` will be included in the output string.

I can see from switching to json output the string itself is parsed correctly, so it seems purely like a decorative issue with the yaml output -- not sure if there is a flag or something I should be using.

**To Reproduce**
I'm mutating a Kubernetes configmap, where the entry itself is a multiline string which is a json style array

```bash
root@Ubuntu-2004-focal-64-minimal /tmp # cat demo.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: example
data:
  versions: |-
    [
      "foo",
      "bar",
      "baz"
    ]
root@Ubuntu-2004-focal-64-minimal /tmp # yq .data.versions demo.yaml
[
  "foo",
  "bar",
  "baz"
]
root@Ubuntu-2004-focal-64-minimal /tmp # dasel select -f demo.yaml '.data.versions'
|-
  [
    "foo",
    "bar",
    "baz"
  ]
root@Ubuntu-2004-focal-64-minimal /tmp # dasel select -f demo.yaml '.data.versions' -w json
"[\n  \"foo\",\n  \"bar\",\n  \"baz\"\n]"
```

I want to select this field as output, parse/process/update the contents of the array, and then put the field back in the yaml doc. emitting the style indicators makes that difficult. 

**Expected behavior**

No style indicators, or an option to emit "raw" output of some form.

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. iOS]: Ubuntu 22.04
- Version [e.g. 22] (`dasel --version`): development-v1.27.2-0.20221006171626-a574326b8d51

**Comment by TomWright** [comment]
I don't have much control over the yaml formatting since an external package is used for that, but since it contains a JSON string there's nothing stopping you from piping 2 dasel commands together to get a plain list of the strings.

Here output the `data.versions` as a plain JSON string:
```bash
$ dasel -f demo.yaml --plain 'data.versions'
[
  "foo",
  "bar",
  "baz"
]
```

And here we take that JSON string, parse it and select all items from the array, and output it using `--plain` to remove any quotes:
```bash
$ echo '[
  "foo",
  "bar",
  "baz"
]' | dasel -r json -m --plain '.[*]'
foo
bar
baz
```

You can then combine those commands as follows:
```bash
$ dasel -f demo.yaml --plain 'data.versions' | dasel -r json -m --plain '.[*]'
foo
bar
baz
```

**Comment by alexeldeib** [comment]
ahh, nice! I missed `--plain`, looks like that can do exactly what I would hope!👍
