### ISSUE TITLE
Multiple selectors

### ISSUE THREAD

**Issue by rothgar** [TomWright/dasel#258]
**Is your feature request related to a problem? Please describe.**
I would like to construct the selector output to allow multiple fields to be selected. Either by passing multiple `-s` flags or adding multiple selector filters to the cli. Similar to the way jq allows multiple fields to be selected. Ideally this would work with csv write parser so I can choose which fields are output

**Describe the solution you'd like**
Using your example json here https://github.com/TomWright/dasel/blob/master/benchmark/data.json I would like to display the following output

```
first,last,model
Tom,Wright,8 Pro
Tom,Wright,iPhone 12
```

Using a command something like this
```
dasel -p json -m '.user.name.first .user.name.last user.phones[*].model'
```

**Describe alternatives you've considered**
Sending the data to `jq` first to select the data into the correct data structure and then use `dasel` to only convert the output.

**Additional context**
My current goal is to take `kubectl get` output and recreate the standard fields as csv. Right now I have to run kubectl to get the headers, run it again to get all the json, filter it with jq, pass it to dasel to change the output from json to CSV

**Comment by TomWright** [comment]
This is a (rather longwinded) way of achieving what you need.

```bash
$ echo '[{"name":"Tom", "things": ["a", "b"]}]' | dasel -r json -m '.[*]' --format '{"name": {{ toRawJson .name }},"thing": "{{range $i, $thing := .things}}{{if gt $i 0}},{{ end }}{{ $thing }}{{end}}"}' | dasel -r json -w csv
name,thing
Tom,"a,b"
```

To break this down:

Original file:
```
[
  {
    "name": "Tom",
    "things": ["a", "b"]
  }
]
```

Dasel command to restructure:
```bash
dasel -r json -m '.[*]' --format '{"name": {{ toRawJson .name }},"thing": "{{range $i, $thing := .things}}{{if gt $i 0}},{{ end }}{{ $thing }}{{end}}"}'
```

With that format string in a nicer format it looks like:
```javascript
{
  "name": {{ toRawJson .name }},
  "thing": "
    {{range $i, $thing := .things}}
      {{if gt $i 0}}
        ,
      {{ end }}
      {{ $thing }}
    {{end}}
  "
}
```

We then have one final `dasel -r json -w csv` to change the file format.

To explain, the `--format` flag overrides the output format and allows you to use a [golang text/template](https://pkg.go.dev/text/template) to format the result as you like. In this case we are simply building a custom JSON object and using some logic to concatenate all of the `things` into a single comma separated string.

All of that said, this isn't far off your jq based solution so i may need to do some thinking here.

**Comment by TomWright** [comment]
The restrict the fields passed in the output we could add an `--only a, b, c` flag, but that doesn't deal with the formatting issue.

**Comment by TomWright** [comment]
I've started work on the `join-to-string` branch that will facilitate a slightly easier way:

```bash
$ cat ./benchmark/data.json | go run cmd/dasel/main.go -r json . --format '{"first": {{ toRawJson .user.name.first }}, "last": {{ toRawJson .user.name.last }}, "model": {{ toRawJson (joinToString (selectMultiple ".phones.[*].model") ",") }}}'
{"first": "Tom", "last": "Wright", "model": "8 Pro,iPhone 12"}
```

A broken down example of that filter:
```javascript
{
    "first": {{ toRawJson .user.name.first }},
    "last": {{ toRawJson .user.name.last }},
    "model": {{
        toRawJson (
            joinToString (
                selectMultiple ".phones.[*].model"
            )
            ","
        )
    }}
}
```

Notice here that we use [`selectMultiple`](https://daseldocs.tomwright.me/usage/flags/format#functions-and-accessors). This essentially allows us to run a subquery within the format template. We then join the results to a single comma separated string and JSON encode that.

**Comment by TomWright** [comment]
One last approach here to give you multiple lines based on a subset of an objects fields:

```bash
$ cat ./benchmark/data.json | dasel -r json . --format '{{ $root := . }}[{{ range $i, $phone := (selectMultiple ".phones.[*]") }}{{ if gt $i 0 }},{{ end }}{"first": {{ toRawJson $root.user.name.first }},"last": {{ toRawJson $root.user.name.last }},"make": {{ format "{{ toRawJson .make }}" $phone }},"model": {{ format "{{ toRawJson .model }}" $phone }}}{{ end }}]' | dasel -r json -w csv
first,last,make,model
Tom,Wright,OnePlus,8 Pro
Tom,Wright,Apple,iPhone 12
```

Here we create an array of JSON objects, then convert that to a CSV.

```javascript
{{ $root := . }}
[
    {{ range $i, $phone := (selectMultiple ".phones.[*]") }}
        {{ if gt $i 0 }}
            ,
        {{ end }}
        {
            "first": {{ toRawJson $root.user.name.first }},
            "last": {{ toRawJson $root.user.name.last }},
            "make": {{ format "{{ toRawJson .make }}" $phone }},
            "model": {{ format "{{ toRawJson .model }}" $phone }}
        }
    {{ end }}
]
```

Note that we have to use `format` to get the `make` and `model` since `selectMultiple` returns `[]*Node` which the templating engine isn't a fan of.

**Comment by rothgar** [comment]
Thanks for all the examples! I just learned that `jq` also supports a `@csv` output option which will for for my use case. I really like the options dasel has but I might just stick with jq for this use case.

**Comment by TomWright** [comment]
No problem at all. If you have any ideas on how I can simplify the experience dasel offers here I'm open to suggestions

**Comment by TomWright** [comment]
Hey @rothgar , just a heads up - you can achieve this with dasel v2 (which is in a pre-release phase).

I added a test for this use-case here: https://github.com/TomWright/dasel/blob/4f9b9480bcdd76afc05bdc4a1599016e77d5839a/internal/command/select_test.go#L92

More information on v2 can be found here: https://daseldocs.tomwright.me/
