### ISSUE TITLE
Windows current build does not output CSV 

### ISSUE THREAD

**Issue by paulidavey** [TomWright/dasel#262]
This is Win10 under bash using the precompiled builds 

$ echo  -e 'users:\n- name: Tom\n- name: Jim' | dasel -r yaml -w csv
users
[map[name:Tom] map[name:Jim]]

$ echo '{
  "users": [
    {
      "name": "Tom"
    },
    {
      "name": "Jim"
    }
  ]
}' |  dasel -r  json -w csv
users
[map[name:Tom] map[name:Jim]]

Same results using
dasel_windows_386.exe
or 
dasel_windows_amd64.exe

(I suggest also adding a -v version number option for tracking)

**Comment by TomWright** [comment]
Hey @paulidavey , which version of dasel are you running? You can find this out by running `dasel -v`.

**Comment by TomWright** [comment]
For reference this issue is solved in `v2`:
```$ echo -e 'users:\n- name: Tom\n- name: Jim' | dasel -r yaml -w csv 'users'
name
Tom
Jim
```
Dasel v2 is in a pre-release state right now but it should be ready to use. You can see the documentation at https://daseldocs.tomwright.me
