### ISSUE TITLE
`put` float value

### ISSUE THREAD

**Issue by JoOkuma** [TomWright/dasel#263]
**Is your feature request related to a problem? Please describe.**

How can I `put` a float value?

```bash
 echo '{}' | dasel put -r json -v 0.5 number
```
returns 0.5 as a string.

**Describe the solution you'd like**

I was hoping to have something similar to:
```bash
 echo '{}' | dasel put -r json -v 0.5 number -t float
```

There might be an alternative approach that I'm not familiar with.

Thanks for implementing and maintaining this tool.

**Comment by TomWright** [comment]
Hey @JoOkuma, good shout this seems to be missing.

I can hopefully implement this tomorrow morning, failing that on Monday. (Europe/London timezone)

**Comment by TomWright** [comment]
Hey @JoOkuma, I've just pushed this to the `master` branch. You can install the development version to access this change immediately

**Comment by JoOkuma** [comment]
Thanks a lot for the quick response.
