### ISSUE TITLE
`join` filter

### ISSUE THREAD

**Issue by IgnisDa** [TomWright/dasel#274]
@TomWright Why was this feature deleted? 

Eg: I would like to join all these elements into a single string via a newline:

<img width="904" alt="image" src="https://user-images.githubusercontent.com/60938164/209463225-619986c4-1847-4882-8fa4-c087814364e9.png">

Here is what I have to do right now, and I want to remove the `jq` usage:

<img width="924" alt="image" src="https://user-images.githubusercontent.com/60938164/209463258-6263603a-81c5-4be3-814d-d7e956479aaf.png">

_Originally posted by @IgnisDa in https://github.com/TomWright/dasel/issues/259#issuecomment-1364653429_

**Comment by TomWright** [comment]
I can work on this after Christmas 👍

**Comment by TomWright** [comment]
`join()` doesn't accept a `\n` (although it could in theory), but it's not needed since output documents are separated by a newline anyway.

Here's an example of `join`, aswell as a newline separated output.

```bash
$ echo '["a","b","c"]' | dasel -r json -w - 'all().join(...)'
a...b...c

$ echo '["a","b","c"]' | dasel -r json -w - 'all()'
a
b
c
```

**Comment by TomWright** [comment]
@IgnisDa We do now have a join func.

If you remove the final `.merge()` from the examples you gave above your issue should be resolved.

**Comment by TomWright** [comment]
Sorry @IgnisDa , last comment.

You can pass a newline to `join`, I was just messing up the passing of the newline character.

```bash
$ echo '{"name":{"first":"Tom","last":"Wright"}}' | dasel -r json -w - 'name.all().join('$'\n'',)'
Tom
Wright
```
