### ISSUE TITLE
Compact output is missing from dasel 2.x

### ISSUE THREAD

**Issue by danielhoherd** [TomWright/dasel#275]
## Description

dasel 1.x had compact output. 2.x is missing that feature.

compact output is mentioned a few times in the [changelog](https://github.com/TomWright/dasel/blob/master/CHANGELOG.md), but the [2.x breaking changes documentation](https://daseldocs.tomwright.me/#v1-to-v2-breaking-changes) does not mention it.

## Example reproduction

```
$ wc -l test.gpx
   26395 test.gpx
$ ./dasel-1.27.3 -r xml -w xml -c -f test.gpx | wc -l
       1
$ ./dasel-2.0.2 -r xml -w xml -c -f test.gpx | wc -l
Error: unknown shorthand flag: 'c' in -c
       0
```

Also there is no mention of compact output in the `--help` text:

```sh
$ ./dasel-1.27.3 --help | grep compact
  -c, --compact                 Compact the output by removing all pretty-printing where possible.
$ ./dasel-2.0.2 --help | grep compact
$
```

## Expected behavior

I would expect compact output to work as it did in 1.x.

**Desktop (please complete the following information):**

- macOS 13.1 22C65 arm64
- `dasel` version 2.0.0, 2.0.2

**Comment by TomWright** [comment]
Hey @danielhoherd,

This should be there. I'll take a look!

Sorry about that

**Comment by TomWright** [comment]
I think you should be able to use `--pretty=false` to achieve the same outcome here.

I missed this change from the docs

**Comment by danielhoherd** [comment]
@TomWright that works!

```
$ ./dasel-1.27.3 -r xml -w json -c -f test.gpx | sha256sum
6c9e233f219ec737448dfb081c3bcc7b5cb9872ac093067fdb380d4840389193  -
$ ./dasel-2.0.0 -r xml -w json --pretty=false -f test.gpx | sha256sum
6c9e233f219ec737448dfb081c3bcc7b5cb9872ac093067fdb380d4840389193  -
```

I'll leave this ticket open due to the documentation omissions.

**Comment by TomWright** [comment]
I've updated the docs with that breaking change now. Thanks for the reminder!
