### ISSUE TITLE
cannot install specific v2 version

### ISSUE THREAD

**Issue by lukas016** [TomWright/dasel#288]
**Describe the bug**
i cannot install specific v2 version with go install:
github.com/tomwright/dasel/v2/cmd/dasel@v2.1.0: github.com/tomwright/dasel@v2.1.0: invalid version: module contains a go.mod file, so module path must match major version ("github.com/tomwright/dasel/v2")

missing v2 suffix for module in go.mod

**To Reproduce**
go install github.com/tomwright/dasel/v2/cmd/dasel@v2.1.0

**Expected behavior**
Install specific version (v1 tags works without problems)

**Comment by TomWright** [comment]
Oh well spotted. I hadn't come across this yes. Thank you

**Comment by TomWright** [comment]
I've just pushed a fix to `master`. I'll release it in the next couple of days

**Comment by TomWright** [comment]
Sorry for the delay. This is now resolved.

```
go install github.com/tomwright/dasel/v2/cmd/dasel@v2.1.1
go install github.com/tomwright/dasel/v2/cmd/dasel@master
```
