### ISSUE TITLE
Filter of elements which not have all attributes / values?

### ISSUE THREAD

**Issue by tobiashochguertel** [TomWright/dasel#303]
I have json data, which has not the same structure for all items in a array. I wanted to filter the items, atm dasel v.2 does not output anything.

Following example:

```shell
echo '[
  {"label":"x","allow":true},
  {"label":"y"},
  {"label":"z","allow":true}
  ]' | dasel -r json 'all().filter(allow)'
```
Output:

```json
```

Expected Output:

```json
{
  "allow": true,
  "label": "x"
}
{
  "allow": true,
  "label": "z"
}
```

I tried also to use `filterOr`, which has the same behavior and doesn't output something when the items in a array have not the same structure:

```shell
echo '[
  {"label":"x","allow":true},
  {"label":"y"},
  {"label":"z","allow":false}
  ]' | dasel -r json 'all().filterOr(allow,equal(label,y))'
```

Output:

```json
```

Expected Output:

```json
{
  "allow": true,
  "label": "x"
}
{
  "label": "y"
}
```

**Comment by TomWright** [comment]
You can use the optional field flag on the property selector: https://daseldocs.tomwright.me/functions/property#property-with-optional-field

```bash
$ echo '[
  {"label":"x","allow":true},
  {"label":"y"},
  {"label":"z","allow":true}
  ]' | dasel -r json 'all().filter(allow?)'
{
  "allow": true,
  "label": "x"
}
{
  "allow": true,
  "label": "z"
}
```
