### ISSUE TITLE
YAML: multiple documents in a single YAML file are not handled correctly

### ISSUE THREAD

**Issue by mortya** [TomWright/dasel#314]
**Describe the bug**
If I have an input YAML file that contains multiple YAML documents and I parse it with dasel (current development version), I get the wrong output.  This is a common use case for a number of tools that produce and consume YAML, including kubernetes and helm.  This likely relates to the "Frontmatter" issue as well: https://github.com/TomWright/dasel/issues/161 .

**To Reproduce**

To reproduce, just run: 
```
$ printf -- '---\na: x\nb: foo\n---\na: y\nc: bar\n' > multi-document.yaml
$ cat multi-document.yaml
---
a: x
b: foo
---
a: y
c: bar
$ ./dasel_linux_amd64 -r yaml . < multi-document.yaml
- a: x
  b: foo
- a: true
  c: bar
```
I.e. dasel converts the YAML from multiple documents into a single document with a top-level array.

Other tools such as yq v4 do the right thing.

**Expected behavior**
Running with "." should get back what I put in

- OS: CentOS7
- Version: "dasel version development" as of 2023-04-04.

**Additional context**

**Comment by TomWright** [comment]
Notes for myself.
The issue is probably in one of the following places:
- https://github.com/TomWright/dasel/blob/3b466e80eabf70b6b39aadb99e43f5fff57ea2ae/storage/yaml.go#L101
- https://github.com/TomWright/dasel/blob/3b466e80eabf70b6b39aadb99e43f5fff57ea2ae/storage/yaml.go#L45

**Comment by TomWright** [comment]
This should now be resolved on the development version.
