### ISSUE TITLE
Dasel can't read arrays from yaml file without hyphen

### ISSUE THREAD

**Issue by EngineerReversed** [TomWright/dasel#315]
**Bug description**
I am trying to read a yaml config file using dasel. However, reading an array from config file leads to reading hyphen into the variable as well. It shouldn't read the hyphen. It is a syntax from yaml file to define array.

**To Reproduce**
_Command:_ 
```
CHROMOSOMES=($(dasel -f $CONFIG_FILE -r yaml CHROMOSOMES))
```

_CONFIG_FILE:_
```
CHROMOSOMES:
  - chr1
  - chr2
  - chr3
```

_GENERATED OUTPUT:_
```
- chr1 - chr2 - chr3
```

_EXPECTED OUTPUT:_
```
chr1 chr2 chr3
```

**Infrastructure:**
```
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.2 LTS
Release:        22.04
Codename:       jammy
Version: dasel version developmentv(2.2.0)
```

**Comment by TomWright** [comment]
You're getting the dashes in your output because it's writing the results as yaml (this is expected).

This should do what you want:
```
$ CHROMOSOMES=($(dasel -f test.yaml 'CHROMOSOMES.all()'))
$ echo $CHROMOSOMES
chr1 chr2 chr3
```
