### ISSUE TITLE
Manual Installation for Windows - Improvement

### ISSUE THREAD

**Issue by maroskukan** [TomWright/dasel#330]
**Is your feature request related to a problem? Please describe.**
In the [Installation manual](https://daseldocs.tomwright.me/installation#manual) Windows section could be improved to provide an example of using powershell to find latest release and download it as it is demonstrated for other platforms.

**Describe the solution you'd like**
Below code snippet could be referenced for ease of use.

```powershell
$releases = curl -sSLf https://api.github.com/repos/tomwright/dasel/releases/latest
Invoke-WebRequest -Uri (($releases | ConvertFrom-Json).assets `
                    | Where-Object { $_.name -eq "dasel_windows_amd64.exe" } `
                    | Select-Object -ExpandProperty browser_download_url) `
                    -OutFile dasel.exe
```

**Describe alternatives you've considered**
Alternative way is to manually click on a release and download via web browser.

**Additional context**

**Comment by TomWright** [comment]
I've added the above to the installation docs in gitbook: https://daseldocs.tomwright.me/installation#windows

**Comment by maroskukan** [comment]
Thanks, I think it would be great to have the code in the Manual section, under Windows "tab". As it accomplishes similar goals as those instructions for Linux and MacOS.

![image](https://github.com/TomWright/dasel/assets/13705278/32c09483-afaa-41c5-be90-bdeefb176cd1)

**Comment by maroskukan** [comment]
To avoid spamming with new Issue, I also noticed that the docker usage example:

```bash
echo '{"name": "Tom"}' | docker run -i --rm ghcr.io/tomwright/dasel:latest -p json '.name'
```
Is no loger valid as it throws an error `Error: unknown shorthand flag: 'p' in -p` 

The updated arguments that work should be as in our readme. 
```bash
echo '{"name": "Tom"}' | docker run -i --rm ghcr.io/tomwright/dasel:latest -r json '.name'
```

**Comment by TomWright** [comment]
Hey @maroskukan,

Thanks for the suggestions I've just made those changes. Appreciate it
