### ISSUE TITLE
Unable to select on CSVs without transforming to a different format

### ISSUE THREAD

**Issue by dragid10** [TomWright/dasel#334]
**Describe the bug**
`dasel` seems unable to just select and display fields on CSV files. Converting csv files to json seems to work fine, but I was hoping to just do selects without having to convert to another format first

Here. is a sample csv
```csv
name,msg
may,yo
june,howdy
july,great
```

**To Reproduce**

```shell
# Version 1
$ dasel -f sample.csv -r csv -s 'name'

Error: cannot use property selector on non map/struct types: slice: property not found: name

# Version 2
$ dasel -f sample.csv -r csv

Error: CSVParser.toBytes cannot handle type []map[string]interface {}

# Version 3
$ dasel -f sample.csv

Error: CSVParser.toBytes cannot handle type []map[string]interface {}

#Version 4 - WORKS
$ dasel -f sample.csv -r csv -w json

[
  {
    "msg": "yo",
    "name": "may"
  },
  {
    "msg": "howdy",
    "name": "june"
  },
  {
    "msg": "great",
    "name": "july"
  }
]

```

Include (sanitized) input files and commands to help along the way.

**Expected behavior**
I expected `dasel` to be able to output the csv when just trying to read a csv file. I also expect to be able to select and filter directly on CSV input without having to convert it to json first. Perhaps this is not the intended way for `dasel` to be used for csv input but there are so few csv examples that it's difficult to tell what is possible 

Essentially something like this:
```shell
# This would just display the whole input
$ dasel -f sample.csv -r csv

name, msg
may, yo
june, howdy
july, great

# This would actually filter the csv input for the whole file
$ dasel -f sample.csv -r csv '.name'

name
may
june
july

# This would actually filter the csv input for a first entry
$ dasel -f sample.csv -r csv '.[0].name'

name
may
```

**Desktop (please complete the following information):**

- OS: `macOS Ventura 13.4`
- Version: `dasel version 2.3.4`

**Comment by TomWright** [comment]
I just did a little testing and can explain what you're seeing.

CSV content:
```
name,msg
may,yo
june,howdy
july,great
```

In JSON form is:
```
[
  {
    "msg": "yo",
    "name": "may"
  },
  {
    "msg": "howdy",
    "name": "june"
  },
  {
    "msg": "great",
    "name": "july"
  }
]
```

It makes sense that `name` doesn't work, because that doesn't exist on an array.

What you can do instead is `all().name`.

You will also need to include a `-w -` to write plain output. Dasel will attempt to use the read parser by default and you can't "csv encode" a single string value.

Complete example:
```
$ echo 'name,msg
may,yo
june,howdy
july,great' | ./dasel -r csv -w - 'all().name'
may
june
july
```

---

The error you got from your 3rd command `dasel -f sample.csv` is unexpected though - I'll have a look at that separate to this issue as the above should solve your problem.

Let me know if this doesn't solve your issue and I can re-open the issue.

**Comment by dragid10** [comment]
Okay this was super helpful! Thanks for walking me through that. It'd definitely be beneficial to include a couple more non-json examples of using `dasel` with different commands. I don't think I would've ever figured this out without your explanation

**Comment by TomWright** [comment]
I have been meaning to do just that, it's just hard to find the time recently
