### ISSUE TITLE
[REG 2.2->2.3] Superfluous quotes in selector output

### ISSUE THREAD

**Issue by orgads** [TomWright/dasel#339]
**Describe the bug**
Selector output is surrounded with quotes, which did not appear in 2.2.0.

**To Reproduce**
test.toml:
```toml
foo = "bar"
```

./dasel-2.2.0 -f test.toml -s foo
```
bar
```

./dasel-2.3.4 -f test.toml -s foo
```
'bar'
```

**Expected behavior**
There should be no quotes.

**Desktop (please complete the following information):**

- OS: Linux
- Version: v2.3.4

**Comment by TomWright** [comment]
This is a change in behaviour in the YAML parser. It is expected because by default it writes values in the same format it reads them.

To completely remove any quotes or YAML formatting from the output you can use `-w -` to use a string output.

**Comment by orgads** [comment]
Thank you. That was really helpful.
