### ISSUE TITLE
Handle quotes in values

### ISSUE THREAD

**Issue by eccles** [TomWright/dasel#340]
**Is your feature request related to a problem? Please describe.**
Some apis (github in this case) return values with embedded quotes

**Describe the solution you'd like**
Handle this correctly (jq does not - invalid numeric literal...
Dasel barfs with Error: could not unmarshal data: could not decode object: invalid character 'a' after object key:value pair

**Describe alternatives you've considered**
Using python or other first class language

**Additional context**
Here is the example output from the Github API whwre the message contains a quote:

{
    "sha":"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "node_id":"yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
    "commit":{
        "author":{
        "name":"alhie",
        "email":"noreply.github.com",
        "date":"2023-06-28T13:27:11Z"
    },
    "committer":{
        "name":"GitHub",
        "email":"noreply@github.com",
        "date":"2023-06-28T13:27:11Z"
    },
    "message":"Revert "added a line to readme to test CICD triggers (#7)" (#8)nnThis reverts commit xxxxxx."
}

**Comment by TomWright** [comment]
That is technically invalid JSON. Those quotes should be escaped.
Is that the exact response you get back?

**Comment by TomWright** [comment]
@eccles please see the above.
An example API call would be great too
