### ISSUE TITLE
Delete selector can't find keys with null values

### ISSUE THREAD

**Issue by srounce** [TomWright/dasel#346]
**Describe the bug**
Delete doesn't work for paths with null values.

**To Reproduce**
```
> echo '{ "foo": null }' | dasel delete -r json 'foo'

< Error: could not access map index: property not found: foo
```

**Expected behavior**
I'd expect it to return `{}` instead I get the error above.

- OS: linux
- Version 2.3.4

**Comment by TomWright** [comment]
I've had a look and this is a tough problem to solve.

Related: https://github.com/golang/go/issues/51649

I'm going to do some thinking and come back to this.

**Comment by TomWright** [comment]
Thanks for your patience on this.

I believe I have resolved this issue, see:
```
$ echo '{"foo":null}' | ./dasel -r json
{
  "foo": null
}
$ echo '{"foo":null}' | ./dasel -r json 'foo'
null
$ echo '{"foo":null}' | ./dasel delete -r json 'foo'
{}
```

The fix is on `master` and I'll create a release shortly.
