### ISSUE TITLE
put string works with 1.0.4, but not with 1.4.0 

### ISSUE THREAD

**Issue by ws-way** [TomWright/dasel#35]
Hello @TomWright ,

I have a problem with my code, it is working with 1.0.4, but not with 1.4.0.

This is my yaml:

```---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: harbor-exporter
  labels:
    app: harbor-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: harbor-exporter
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: harbor-exporter
    spec:
      serviceAccountName: default
      restartPolicy: Always
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: harbor-exporter
          image: "c4po/harbor-exporter:debug"
          imagePullPolicy: Always
          env:
            - name: HARBOR_URI
#            name of the Service for harbor-core
              value: http://harbor-core.harbor # change prefix to the name of your Helm release
            - name: HARBOR_USERNAME
              value: "admin"
            - name: HARBOR_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: harbor-core # change prefix to the name of your Helm release
                  key: HARBOR_ADMIN_PASSWORD

          securityContext:
            capabilities:
              drop:
                - SETPCAP
                - MKNOD
                - AUDIT_WRITE
                - CHOWN
                - NET_RAW
                - DAC_OVERRIDE
                - FOWNER
                - FSETID
                - KILL
                - SETGID
                - SETUID
                - NET_BIND_SERVICE
                - SYS_CHROOT
                - SETFCAP
            readOnlyRootFilesystem: true
          resources:
            limits:
              cpu: 400m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 64Mi
          ports:
            - containerPort: 9107
              name: http
          livenessProbe:
            httpGet:
              path: /-/healthy
              port: http
            initialDelaySeconds: 5
            timeoutSeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /-/ready
              port: http
            initialDelaySeconds: 1
            timeoutSeconds: 5
            periodSeconds: 5
```
I am executng this:
```
dasel put string -f $file '.metadata.namespace' 'registry'
local_harbor_core_service_name=`kubectl get svc -n registry | grep harbor-core | awk '{print $1}'`
local_harbor_core_service_name will be harbor.harbor.core
dasel put string -f $file -s "spec.template.spec.containers.(name=harbor-exporter).env.(name=HARBOR_URI).value" "http://"$local_harbor_core_service_name
```
The value for HARBOR_URI is not changed anymore under 1.4.0 and the layout is not correct anymore.

This is the output with 1.0.4

```apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: harbor-exporter
  name: harbor-exporter
  namespace: registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: harbor-exporter
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: harbor-exporter
    spec:
      containers:
      - env:
        - name: HARBOR_URI
          value: http://harbor-harbor-core
        - name: HARBOR_USERNAME
          value: admin
        - name: HARBOR_PASSWORD
          valueFrom:
            secretKeyRef:
              key: HARBOR_ADMIN_PASSWORD
              name: harbor-core
        image: c4po/harbor-exporter:debug
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /-/healthy
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 5
        name: harbor-exporter
        ports:
        - containerPort: 9107
          name: http
        readinessProbe:
          httpGet:
            path: /-/ready
            port: http
          initialDelaySeconds: 1
          periodSeconds: 5
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 400m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 64Mi
        securityContext:
          capabilities:
            drop:
            - SETPCAP
            - MKNOD
            - AUDIT_WRITE
            - CHOWN
            - NET_RAW
            - DAC_OVERRIDE
            - FOWNER
            - FSETID
            - KILL
            - SETGID
            - SETUID
            - NET_BIND_SERVICE
            - SYS_CHROOT
            - SETFCAP
          readOnlyRootFilesystem: true
      restartPolicy: Always
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      serviceAccountName: default

**Comment by TomWright** [comment]
Thanks for raising this issue. I'll take a look at it

**Comment by TomWright** [comment]
@ws-way I've found and resolved the issue in `v1.4.1`. I introduced a bug that went undetected when I added sub-selector functionality. I've got an additional test in place now so this shouldn't happen again.

Thanks for your help with dasel!

**Comment by ws-way** [comment]
Hello @TomWright ,

Thanks, but there is still something wrong.

original:

`apiVersion: apps/v1
kind: Deployment
metadata:
  name: harbor-exporter
  labels:
    app: harbor-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: harbor-exporter
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: harbor-exporter
    spec:
      serviceAccountName: default
      restartPolicy: Always
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: harbor-exporter
          image: "c4po/harbor-exporter:debug"
          imagePullPolicy: Always
          env:
            - name: HARBOR_URI
              value: http://harbor-core.harbor # change prefix to the name of your Helm release`

Running: dasel put string -m -f ./harbor-exporter.yaml '.[*].metadata.namespace' 'registry'

`apiVersion: v1
kind: Service
metadata:
  labels:
    app: harbor-exporter
  name: harbor-exporter
  namespace: registry
spec:
  ports:
  - name: http
    port: 9107
    protocol: TCP
  selector:
    app: harbor-exporter
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: harbor-exporter
  name: harbor-exporter
  namespace: registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: harbor-exporter
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: harbor-exporter
    spec:
      containers:
      - env:
        - name: HARBOR_URI
          value: http://harbor-core.harbor
        - name: HARBOR_USERNAME
          value: admin
        - name: HARBOR_PASSWORD
          valueFrom:
            secretKeyRef:
              key: HARBOR_ADMIN_PASSWORD

Please look at -env, this is incorrect.

Thanks
`

**Comment by TomWright** [comment]
Can you provide the full input file please? (make sure you wrap it in code tags so as the formatting is maintained)

As far as I can tell this is working as expected now: https://dasel.tomwright.me/s/2532f8ea-bd2b-42a2-8f9e-8a329ef3a1f8

The container definition now starts with `- env` which means the output ordering has changed as per [https://github.com/TomWright/dasel#preserved-formatting-and-ordering](preserved formatting and ordering), but the content is still good and valid.

**Comment by ws-way** [comment]
I have tested it with your playground and it looks not ok to me. See the -env.

![image](https://user-images.githubusercontent.com/71637976/98934368-42fcba80-24e2-11eb-880e-8b16b7313715.png)


`
apiVersion: apps/v1
kind: Deployment
metadata:
  name: harbor-exporter
  labels:
    app: harbor-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: harbor-exporter
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: harbor-exporter
    spec:
      serviceAccountName: default
      restartPolicy: Always
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: harbor-exporter
          image: "c4po/harbor-exporter:debug"
          imagePullPolicy: Always
          env:
            - name: HARBOR_URI
              value: http://harbor-core.harbor # change prefix to the name of your Helm release
            - name: HARBOR_USERNAME
              value: "admin"
            - name: HARBOR_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: harbor-core # change prefix to the name of your Helm release
                  key: HARBOR_ADMIN_PASSWORD
          securityContext:
            capabilities:
              drop:
                - SETPCAP
                - MKNOD
                - AUDIT_WRITE
                - CHOWN
                - NET_RAW
                - DAC_OVERRIDE
                - FOWNER
                - FSETID
                - KILL
                - SETGID
                - SETUID
                - NET_BIND_SERVICE
                - SYS_CHROOT
                - SETFCAP
            readOnlyRootFilesystem: true
          resources:
            limits:
              cpu: 400m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 64Mi
          ports:
            - containerPort: 9107
              name: http
          livenessProbe:
            httpGet:
              path: /-/healthy
              port: http
            initialDelaySeconds: 5
            timeoutSeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /-/ready
              port: http
            initialDelaySeconds: 1
            timeoutSeconds: 5
            periodSeconds: 5
`

**Comment by TomWright** [comment]
Yes I see what you are talking about - that's what I meant with this statement:
> The container definition now starts with - env which means the output ordering has changed as per [preserved formatting and ordering](https://github.com/TomWright/dasel#preserved-formatting-and-ordering), but the content is still good and valid.

The values within the container document have been re-ordered, but they are all there and present with the correct values, right?

**Comment by ws-way** [comment]
it looks indeed that it is working, thanks!
