### ISSUE TITLE
Special characters inside string literals are replaced with Unicode escape sequences in JSON

### ISSUE THREAD

**Issue by ian-eulith** [TomWright/dasel#351]
Hi there! I upgraded to the latest version of dasel in order to get [this PR](https://github.com/TomWright/dasel/pull/289), but ran into a different bug that I'd like to report.

**Describe the bug**

Special characters -- ampersands and angle brackets -- that are inside string literals are replaced with Unicode escape sequences (e.g., `\u0026`) when using `dasel put` with a JSON file.

**To Reproduce**

1. Copy the JSON file below somewhere.
2. Run `dasel put -t string -f path/to/test.json '.field1' -v "B"`

```json
{
  "field1": "A",
  "field2": "A > B && B > C"
}
```

**Expected behavior**
The value of `field1` is replaced with `"B"` and `field2` is unchanged.

**Actual behavior**
`field1` is replaced correctly, but `field2` is changed to `"A \u003e B \u0026\u0026 B \u003e C"`.

**Desktop (please complete the following information):**

- OS: macOS Ventura 13.5 (M1)
- Version: 2.3.4 (using a prebuilt `dasel_darwin_arm64` binary)

**Comment by TomWright** [comment]
I have found the cause of this.
EscapeHTML is false on the JSON encoder, however it's delegating JSON marshaling to https://github.com/TomWright/dasel/blob/80b13f376eb2ffe5e9ab0582f69fc8be18140296/dencoding/json_encoder.go#L66, which isn't using the same JSON encoder.

**Comment by TomWright** [comment]
This has been fixed and is released under `v2.4.1`.
