### ISSUE TITLE
[BUG] Dasel crash when reading an empty file

### ISSUE THREAD

**Issue by Larandar** [TomWright/dasel#374]
**Describe the bug**

Dasel will crash if called on an empty file, even if it's ~~by specification~~ *in most implementations interpreted as*  a valid file for that format (yaml and toml).

(Yes, I just read both TOML and YAML specs, and it's ambiguous as in both case an unquoted empty string is corresponding to `nil` but the lexer seems to assume at least one identifier) 

**To Reproduce**

```sh
touch /tmp/bug.toml
dasel -f /tmp/bug.toml
```

Will fail:

```
panic: reflect: call of reflect.Value.Interface on zero Value

goroutine 1 [running]:
reflect.valueInterface({0x0?, 0x0?, 0x0?}, 0x0?)
	reflect/value.go:1495 +0xfc
reflect.Value.Interface(...)
	reflect/value.go:1490
github.com/tomwright/dasel/v2.Value.Interface({{0x0, 0x0, 0x0}, 0x0, 0x0, 0x0})
	github.com/tomwright/dasel/v2/value.go:55 +0x6c
...
```

**Expected behavior**

Such files should be handled like most parsers interpreted it, so `nil`. This way creating a new toml file can be as simple as:

```sh
touch /tmp/state.toml
dasel put -f /tmp/toml .state.last-execution -t string -v $(date -Iseconds)
```

**Desktop (please complete the following information):**

- OS: macOS 14.1
- Version: `dasel version 2.4.1`

**Comment by TomWright** [comment]
Thanks for highlighting this @Larandar .

Dasel has an issue with nulls at the moment, stemming from the fact that it uses reflection internally. That said, it shouldn't be too hard to get this working. I'll work on this soon.

**Comment by TomWright** [comment]
I think I accidentally broke this by commenting this out: https://github.com/TomWright/dasel/blob/3bfb5dd1b1415b009ebf06660225a9e2de772523/internal/command/select.go#L107

I'll try and verify this tonight

**Comment by TomWright** [comment]
This has been fixed in the development release and will be released soon.

**Comment by Larandar** [comment]
Ha, the good old "I'm sure this code is not applicable anymore" 👍

**Comment by TomWright** [comment]
Hey @Larandar,

This was included in the last release.

```
$ dasel -v
dasel version 2.5.0
$ touch empty.toml
$ dasel -f empty.toml

```
