### ISSUE TITLE
Suppress header generation

### ISSUE THREAD

**Issue by lifeboy** [TomWright/dasel#381]
I use a bash for loop to generate output of for a list a virtual machines running in proxmox, but header iteration creates a json output, for which dasel generates a set of headers.  How can one suppress the header generation?

`:~# pvesh get /nodes/FT1-NodeA/qemu/110/config --noheader --output-format json
`
which results in:

`{"agent":"1","bootdisk":"virtio0","cores":1,"digest":"4daef6f23dc4f7ddfe4ee15197701e0d7feeefd1","ide2":"none,media=cdrom","memory":1024,"name":"imb03","net0":"virtio=A6:54:4A:7F:FB:58,bridge=vmbr0","numa":0,"onboot":1,"ostype":"l26","scsihw":"virtio-scsi-pci","smbios1":"uuid=041640a0-1686-48b2-b8e7-8f159f6b733b","sockets":1,"virtio0":"standard:vm-110-disk-0,size=50G"}
`
So I write that to a file using jq to only extract what I need.

`# first write a header
:~# echo 'name,cores,memory,virtio,virtio1,scsi0,scsi1' >qemu.config
:~# pvesh get /nodes/FT1-NodeA/qemu/110/config --noheader --output-format json| jq '{name:.name, cores:.cores, memory:.memory, virtio0:.virtio0, virtio1:.virtio1, scsi0:.scsi0, scsi1:.scsi1}' >> qemu,config`

I use a for loop to get the config for each vm.

```
:~# cat qemu.config
{
  "name": "eagle",
  "cores": 6,
  "memory": 16384,
  "virtio0": "standard:vm-111-disk-0,size=100G",
  "virtio1": null,
  "scsi0": null,
  "scsi1": null
}
{
  "name": "BI-Joe",
  "cores": 2,
  "memory": 12288,
  "virtio0": "standard:vm-114-disk-0,discard=on,iothread=1,size=100G",
  "virtio1": null,
  "scsi0": null,
  "scsi1": null
}
<snip>
```

Now I feed the result to dasel, but there doesn't seem to be a way to suppress the headers.

```
:~# /usr/local/bin/dasel -r json -w csv < qemu.config 
name,cores,memory,virtio0,virtio1,scsi0,scsi1
eagle,6,16384,"standard:vm-111-disk-0,size=100G",null,null,null
name,cores,memory,virtio0,virtio1,scsi0,scsi1
BI-Joe,2,12288,"standard:vm-114-disk-0,discard=on,iothread=1,size=100G",null,null,null
<snip>
```

What can I do to fix this?  I need to get:

```
name,cores,memory,virtio0,virtio1,scsi0,scsi1
eagle,6,16384,"standard:vm-111-disk-0,size=100G",null,null,null
BI-Joe,2,12288,"standard:vm-114-disk-0,discard=on,iothread=1,size=100G",null,null,null
<snip>

```

**Comment by TomWright** [comment]
You are providing multiple JSON documents and converting them to CSV, resulting in multiple CSV documents. This is why the headers are repeated.

Option 1, merge all of the given documents documents into a single array of items:
```
$ echo '{
  "name": "eagle",
  "cores": 6,
  "memory": 16384,
  "virtio0": "standard:vm-111-disk-0,size=100G",
  "virtio1": null,
  "scsi0": null,
  "scsi1": null
}
{
  "name": "BI-Joe",
  "cores": 2,
  "memory": 12288,
  "virtio0": "standard:vm-114-disk-0,discard=on,iothread=1,size=100G",
  "virtio1": null,
  "scsi0": null,
  "scsi1": null
}' | dasel -r json -w csv 'all().merge()'
```

Option 2, just give dasel an array of objects in a single document:
```
$ echo '[
{
  "name": "eagle",
  "cores": 6,
  "memory": 16384,
  "virtio0": "standard:vm-111-disk-0,size=100G",
  "virtio1": null,
  "scsi0": null,
  "scsi1": null
},
{
  "name": "BI-Joe",
  "cores": 2,
  "memory": 12288,
  "virtio0": "standard:vm-114-disk-0,discard=on,iothread=1,size=100G",
  "virtio1": null,
  "scsi0": null,
  "scsi1": null
}
]' | dasel -r json -w csv
cores,memory,name,scsi0,scsi1,virtio0,virtio1
6,16384,eagle,null,null,"standard:vm-111-disk-0,size=100G",null
2,12288,BI-Joe,null,null,"standard:vm-114-disk-0,discard=on,iothread=1,size=100G",null
```
