### ISSUE TITLE
Is it possible to get a raw value, i.e. without quotes?

### ISSUE THREAD

**Issue by manfredlotz** [TomWright/dasel#387]
Reading a TOML file I would like to get a string without quotes. I am imagining an option `--raw` for this.

Example
```
[guide]
regex = "The answer is 42"
```
`dasel -f guide.toml -r toml 'guide.regex'`  gives `'The answer is 42'`

I would like to get `The answer is 42`

Or is this possible and I just did not find how to do?

**Comment by TomWright** [comment]
Hey @manfredlotz, you're looking for `-w -` or `-w plain` (aliases of eachother).

I appreciate the docs could be better here but the reference is here: https://daseldocs.tomwright.me/supported-file-formats

**Comment by manfredlotz** [comment]
Thanks a lot. I have to admit that I wasn't really aware of `-w`.  Tested, and (no surprice) working fine.

Perhaps it would be good to also add a sentence to say that the plain parser emits the raw values.

**Comment by TomWright** [comment]
Agreed. I've been meaning to put some time aside to improve the docs

**Comment by TomWright** [comment]
Hey, yes this wasnt in the initial V3 release.

Good reminder though - I need to figure out exactly how the output should be formatted. It's easy enough for scalar values but arrays and objects are a little more awkward until I know some use cases.

**Comment by bravely-beep** [comment]
Any updates on this? I'd quite like to be able to print unquoted strings to store in bash or make variables.

**Comment by TomWright** [comment]
The `plain` output format is being added to V3, sorry for the wait. It will included in the next release
