### ISSUE TITLE
How to iterate?

### ISSUE THREAD

**Issue by manfredlotz** [TomWright/dasel#389]
Sorry, if I was just not able to find the relevant documentation entry.

I have something like this:

``` 
[p.a]
some = "hey"
[p.bla]
some = "some val"
```
In a shell script I like to iterate over [p] and work on the values.

**Comment by TomWright** [comment]
Without knowing what you want to do it's hard to help, but here's a sample script where we loop through the `a` and `bla` keys and access `some` within them.

```
#!/bin/sh

for key in $(dasel -f ./file.toml -w - 'p.keys().all()')
do
        some=$(dasel -f ./file.toml -w - "p.${key}.some")
        echo "found ${some} in ${key}"
done
```

```
$ ./do.sh
found hey in a
found some val in bla
```

**Comment by manfredlotz** [comment]
Yes, that was what I was after. Thanks a lot and sorry for not seeing it myself.
