### ISSUE TITLE
Select element by name

### ISSUE THREAD

**Issue by abitrolly** [TomWright/dasel#39]
I'd like to select all elements named `apple`. Doesn't seem to be possible with the current `dasel`.

```xml
...
<food>
  <tart>
    <apple color="yellow"/>
  </tart>
  <pie>
    <crust quality="flaky"/>
    <filling>
      <apple color="red"/>
    </filling>
  </pie>
  <apple color="green"/>
</food>
...
```

In XPath it would be `.//apple`

https://stackoverflow.com/questions/15077462/xpath-to-select-all-elements-with-a-specified-name

**Comment by TomWright** [comment]
Hi @abitrolly,

Thanks for your question.

You are correct in saying this isn't currently possible with dasel. It is however a feature I've been thinking about and this gives me the motivation to push forward and implement it.

I've created a more detailed feature request for a more generic search selector here: https://github.com/TomWright/dasel/issues/40

Please review it and provide any feedback you may have. I'll start implementing it soon and expect to have a first working version in the next couple of days.
