### ISSUE TITLE
Supported toml version?

### ISSUE THREAD

**Issue by rszyma** [TomWright/dasel#395]
**Is your feature request related to a problem? Please describe.**
I cannot find any information about supported toml version by dasel.

**Describe the solution you'd like**
Put a minimal supported version of toml in README.

**Describe alternatives you've considered**
Browsing thought source code, but it would be nice to know at the first glance what toml version is supported.

**Additional context**
None

**Comment by TomWright** [comment]
Dasel supports TOML via [pelletier/go-toml](https://github.com/pelletier/go-toml).

That package supports TOML v1.0.0 - I updated the dasel docs (under [support file formats](https://daseldocs.tomwright.me/supported-file-formats)) to subtly highlight that.
