### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by TomWright** [TomWright/dasel#40]
**Is your feature request related to a problem? Please describe.**
There is no way to search documents when you don't know the structure.
Related issues: https://github.com/TomWright/dasel/issues/39

**Describe the solution you'd like**
A new selector syntax for searching: `(?:key=value)`.

This is a multi-select selector.

It will search the current + all child nodes using the key as the query.

If the key is `.` or `value` then compare the actual value of the node.

If the key is `-` or `keyValue` then compare the "key" of the node.

This should work in both `select` and `put` commands.

**Describe alternatives you've considered**
A new `search` command, but that complicates things when you want to select further values or update values.

**Additional context**
Example usage may look like:

```
<food>
  <tart>
    <apple color="yellow"/>
  </tart>
  <pie>
    <crust quality="flaky"/>
    <filling>
      <apple color="red"/>
    </filling>
  </pie>
  <apple color="green"/>
</food>
```

```
dasel -f in.xml -m '.food.(?:keyValue=apple)'
<apple color="yellow"/>
<apple color="red"/>
<apple color="green"/>
```

**Comment by abitrolly** [comment]
The same query XPath is `food//apple`.
```bash
$ xpath -q -e "food//apple" < in.xml
<apple color="yellow" />
<apple color="red" />
<apple color="green" />
```
Note that it doesn't search on attribute names.

Search for elements with specified attributes uses brackets.
```bash
$ xpath -q -e "food//apple[@color='red']" < a
<apple color="red" />
```

**Comment by TomWright** [comment]
The equivalent attribute from this suggestion would like like this:
```
dasel -f in.xml -m '.food.(?:keyValue=apple).(-color=red)'
```

**Comment by TomWright** [comment]
Hi @abitrolly,

I've implemented this in https://github.com/TomWright/dasel/pull/43.

There's a slight change in relation to the previous explanations above though due to the way XML documents are represented within dasel.

At the time of writing the results to output dasel is only aware of the node (xml tag in this case) content, meaning the XML output looks like this:

```
<-color>yellow</-color>
<-color>red</-color>
<-color>green</-color>
```

This obviously isn't desired depending on how you plan on using this feature.

You can still extract the colour of each apple with the following: `'.(?:-=apple).-color'`
```
yellow
red
green
```

I haven't yet come up with a way to satisfy the XML output without messing with the output/processing of all other data formats - does this implementation cover your current needs?

**Comment by abitrolly** [comment]
@TomWright I didn't though that XML attributes don't map to other formats like YAML and JSON clearly. That is a challenge, indeed. For my use case I used `xpath`. I didn't need attribute values, so this worked for me.

```
osc api "/distributions" | xpath -q -e "//distribution/reponame/text()"
```

Speaking of universal language to access this data accross formats, maybe it makes sense to use stripped XPath for YAML and JSON queries.

**Comment by TomWright** [comment]
Good to hear you found a solution.

I'm going to go ahead and merge the search functionality as it is for now since it still serves a purpose.

I will keep thinking about a better way to render the final XML but it's tough.
