### ISSUE TITLE
How do I do with this kind of error

### ISSUE THREAD

**Issue by yejiawei1234** [TomWright/dasel#47]
**Describe the desired outcome**
Using dasel to select json file, but this error occur

Error: could not load input: could not unmarshal config data: invalid character '{' after top-level value

**Resources**
My json file content is like this 
{"topic": "test", "device_info": {"device_name": "apple"}, "message": "failed"}

**Comment by TomWright** [comment]
Hi @yejiawei1234,

I can't seem to replicate this: https://dasel.tomwright.me/s/0027d179-b522-4ae0-9153-f6ae9f46c431

What's the full command you're running?

**Comment by yejiawei1234** [comment]
Hi @TomWright , 
thanks for your reply
I just download this repo and want to run it in Goland. I get this error message after I try to build /Desktop/dasel-master/cmd/dasel/main.go. 

/usr/local/go/bin/go build -o /private/var/folders/50/v5346r4n67573r8nd1437zwh0000gn/T/___go_build_main_go /Users/jack/Desktop/dasel-master/cmd/dasel/main.go #gosetup
/private/var/folders/50/v5346r4n67573r8nd1437zwh0000gn/T/___go_build_main_go -f /Users/jack/Desktop/test.json
Error: could not load input: could not unmarshal config data: invalid character '{' after top-level value
Usage:
  dasel select -f <file> -p <json,yaml> -s <selector> [flags]

Flags:
  -f, --file string       The file to query.
  -h, --help              help for select
  -m, --multiple          Select multiple results.
  -p, --parser string     The parser to use with the given file.
      --plain             Do not format output to the output data format.
  -s, --selector string   The selector to use when querying the data structure.

Error: could not load input: could not unmarshal config data: invalid character '{' after top-level value

**Comment by TomWright** [comment]
What does your build configuration in Goland look like? It looks like you may not have it set up correctly.

This works for me:

![image](https://user-images.githubusercontent.com/935867/99648306-ccfcd400-2a4a-11eb-93b3-45cc3b16ce72.png)

**Comment by TomWright** [comment]
Notice that you'll have to specify a file to work with since you're not able to pipe data into the command this way.

**Comment by yejiawei1234** [comment]
Hi @TomWright 
Thanks for your reply. It really weird. The setting is almost the same but I still got the error message.
<img width="1071" alt="image" src="https://user-images.githubusercontent.com/7010533/99675071-bb024c00-2ab1-11eb-8a11-b94617737a1a.png">

error message is still the same

/usr/local/go/bin/go build -o /private/var/folders/50/v5346r4n67573r8nd1437zwh0000gn/T/___go_build_github_com_tomwright_dasel_cmd_dasel . #gosetup
/private/var/folders/50/v5346r4n67573r8nd1437zwh0000gn/T/___go_build_github_com_tomwright_dasel_cmd_dasel -f /Users/jack/Desktop/test.json
Error: could not load input: could not unmarshal config data: invalid character '{' after top-level value
Usage:
  dasel select -f <file> -p <json,yaml> -s <selector> [flags]

Flags:
  -f, --file string       The file to query.
  -h, --help              help for select
  -m, --multiple          Select multiple results.
  -p, --parser string     The parser to use with the given file.
      --plain             Do not format output to the output data format.
  -s, --selector string   The selector to use when querying the data structure.

Error: could not load input: could not unmarshal config data: invalid character '{' after top-level value

**Comment by TomWright** [comment]
It looks like the issue is your JSON file then. Can you copy it's contents here?

**Comment by yejiawei1234** [comment]
I finally got it. If the file content is

**Comment by yejiawei1234** [comment]
I finally got it. If the content is 
{"topic": "1", "device_info": {"device": "apple"}, "message": "ignored"}
It works
<img width="1216" alt="image" src="https://user-images.githubusercontent.com/7010533/99676797-e84ff980-2ab3-11eb-89a0-cbe7160e3988.png">


but if it is 
{"topic": "1", "device_info": {"device": "apple"}, "message": "ignored"}
{"topic": "1", "device_info": {"device": "apple"}, "message": "ignored"}
then there is the error message
<img width="1205" alt="image" src="https://user-images.githubusercontent.com/7010533/99676857-fd2c8d00-2ab3-11eb-93b8-c37f2f433ca9.png">

**Comment by TomWright** [comment]
I'm glad you found it 🙂 

That's good timing actually - as of `v1.6.2` dasel supports multi-document JSON files.

Pull from `master` and try again

**Comment by yejiawei1234** [comment]
Big thanks!
