### ISSUE TITLE
Data format discovery

### ISSUE THREAD

**Issue by TomWright** [TomWright/dasel#5]
**Is your feature request related to a problem? Please describe.**
It would be nice if dasel could guess the data format when a parser is not defined.

**Describe the solution you'd like**
Dasel will look at the given input and discover the data format (JSON for example).

This means the parser flag will no longer be required.

**Discovery**
How do we actually detect the file type?

If it starts with `<` it's XML.
If it starts with `{` it's JSON.
If it starts with `[` and ends with `]` it's JSON.
If it starts with `[` and doesn't end with `]` it's TOML.
If the first and second lines contain the same number of comma's it's CSV.
Otherwise it's YAML.

These are some pretty basic checks which could easily be caught out, but for general usage it should be good enough.

**Comment by ewen-lbh** [comment]
You could also use `encoding/json`'s `Validate` (I guess that packages to marshal/unmarshal also have an equivalent function), it'd complement those basic checks

**Comment by TomWright** [comment]
Thanks for your input.

That does have drawbacks of potentially unmarshalling the entire document twice - once when finding the parser and again to do the lookup.

With some re-working of the logic it's possible to only unmarshal the data once in which case this would be great.

I'll leave this here for further ideas and input before I start working on it.
