### ISSUE TITLE
Install dasel with scoop command-line software installer

### ISSUE THREAD

**Issue by littleli** [TomWright/dasel#54]
I think dasel is interesting enough tool to be included in Scoop bucket (repository) and should be installable with this popular package manager. I already initiated PR to scoop extras and hopefully soon this going to be available.

PR is in progress here: https://github.com/lukesampson/scoop-extras/pull/5220

Are you interested in an update on installation instructions once it's merged?

**Comment by TomWright** [comment]
Great idea, I've been meaning to submit dasel to homebrew etc but haven't gotten round to it yet.

Sure go ahead and submit a PR when it's available.

Thanks for the contribution 🙂

**Comment by littleli** [comment]
#55
