### ISSUE TITLE
jq-like builtin function support

### ISSUE THREAD

**Issue by magodo** [TomWright/dasel#57]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated about how to get all the keys in a map, which has several nested levels. In `jq`, I can use the builtin function `keys[]` after a pipe.

**Describe the solution you'd like**
I hope the selector used in `dasel` can also support the pipe together with some handy builtin functions.

**Comment by TomWright** [comment]
Hi @magodo, thanks for raising this issue!

Could I ask you to provide an example to make sure I fully understand your request please?

**Comment by magodo** [comment]
Something like this:

```shell
$ cat << EOF | jq 'keys[]'
{
"a": {},
"b": {}
}
EOF
"a"
"b"
```

**Comment by TomWright** [comment]
This has been implemented in https://github.com/TomWright/dasel/pull/62 and will be included in the next release.

The syntax is ```
echo `{"a":{},"b":{}}` | dasel -p json '.-'
```

Where the usage of `-` in the property selector tells dasel to return the keys/indexes of the current node.

**Comment by magodo** [comment]
@TomWright Great job :+1:
