### ISSUE TITLE
Ability to return a null value when nothing returned

### ISSUE THREAD

**Issue by chiqomar** [TomWright/dasel#59]
**Is your feature request related to a problem? Please describe.**
When using jq, if you reference a key that does not exist, jq will throw an error about not finding a value, and return the value `null`. This same behavior is not true of dasel; if setting a variable to the output of a dasel command that cannot be found, the variable is set to the error blurb.

**Describe the solution you'd like**
Either the default behavior, or the ability with a switch, to output a value that can be used for comparison, like `null` or `none`, or even an empty string, so it can be used cleanly in scripts.

**Describe alternatives you've considered**
I have thought about just piping everything to /dev/null, and using the return code for finding success, but that only works in the negative case; to get the value I want, I have to run dasel again, which I guess could work. Ideally, I could run once and be good.

**Additional context**
I am attempting to replace some code that is written as follows:
```bash
SCHEDULE=$(jq -r .[$i].schedule ${CONFIG} | sed 's/\*/\\*/g')
if [ "${SCHEDULE}" == "null" ]; then
	echo "Schedule Missing: $(jq -r .[$i].schedule ${CONFIG})"
	continue
fi
```

**Comment by TomWright** [comment]
Should it return `null` in place of any error? Or just not found?

For example, querying a property that doesn't exist is considered not found, but using a selector on an invalid type is a different type of error.

The full list of errors can be found here: https://github.com/TomWright/dasel/blob/d140860feae550f2838329c3a12d05fd07beea4c/error.go

**Comment by chiqomar** [comment]
I think that the priority is `ValueNotFound`, per what you did in the PR. I think it may make sense to `InvalidIndexErr`, as it is a related error (and jq reacts to a bad index the same way it does an nil property), and stretching slightly, `UnexpectedPreviousNilValue` could be added as well, but not sure if that makes as much sense.

**Comment by TomWright** [comment]
I think it makes sense for it to handle these errors:
- `InvalidIndexErr` - Bad index in an array
- `UnsupportedSelector` - Used an array index on an object for example
- `ValueNotFound` - Property not found

I'm not going to override `UnexpectedPreviousNilValue` since that highlights more of an error within dasel's data parsing rather than a missing value.

**Comment by chiqomar** [comment]
I will note that in the `UnsupportedSelector` case, `jq` errors out.

**Comment by TomWright** [comment]
That's food for thought. I guess the implementation will depend on your usage and understanding of the data.

Perhaps an `UnsupportedSelector` should error out. I think if I were to use this functionality the actual error may be more useful to me. Do you have any preference on this?

**Comment by chiqomar** [comment]
I think it does make sense for `UnsupportedSelector` to error out, the user should know that they are accessing the data incorrectly, not that the index is off or that a key is missing.

**Comment by TomWright** [comment]
This has now been merged and will be included in the next release.

I've opted to only support `ValueNotFound` and you can enable this feature with the `-n`,`--null` flag.
