### ISSUE TITLE
installable from ASDF-VM

### ISSUE THREAD

**Issue by ghostsquad** [TomWright/dasel#78]
This is a request to support asdf-vm

I've filed an issue here to make a repo for dasel. Maybe you can comment on that issue to get maintainership of the repo once created?

I can contribute to the creation of the plugin, but it's already very very simple, and you can copy/paste from other Github-based plugins.
https://github.com/asdf-community/.github/issues/11

**Comment by TomWright** [comment]
Thanks for your contribution!

I'd be happy if you could contribute to the creation of the plugin. I've not used nor created any asdf plugins before.

I do have plans to release dasel on other package managers (homebrew for example) but haven't gotten round to it yet.

**Comment by TomWright** [comment]
Hey @ghostsquad,

I see that the required repo has been created on the asdf side: https://github.com/asdf-community/asdf-dasel

Are you planning on setting this up?

**Comment by ghostsquad** [comment]
I am indeed. I'll do it this weekend.

**Comment by ghostsquad** [comment]
depends on #83

**Comment by ghostsquad** [comment]
almost there!
https://github.com/asdf-vm/asdf-plugins/pull/346?ts=4

Once this is merged, I'll submit a PR here to update the readme. 😄
