### ISSUE TITLE
compact Output mode?

### ISSUE THREAD

**Issue by tobiashochguertel** [TomWright/dasel#81]
I was asking me if this is already possible but I didn't found an answer yet,

`jq` has a `-c` option which means: `  -c               compact instead of pretty-printed output;`

is that possible to add to `dasel` or has dasel such an option already?

**Comment by TomWright** [comment]
There isn't an equivalent flag in dasel as of yet.

I can add this as a `-c`, `--compact` flag.

**Comment by tobiashochguertel** [comment]
if you want, I think that would be nice for me. I use the -c property to get something in one-line output (okay it's not working everytime correctly with `jq` but, it's for me then often easier to script something in a ci-pipeline step.

**Comment by TomWright** [comment]
Sure thing. That sounds reasonable. I'll work on this over the weekend 🙂

**Comment by TomWright** [comment]
@tobiashochguertel This is supported as of `v1.12.0`.

Without `-c`:
```
$ echo '{"name":"Tom"}' | dasel put string -p json '.colour' red 
{
  "colour": "red",
  "name": "Tom"
}
```

With `-c`:
```
$ echo '{"name":"Tom"}' | dasel put string -p json -c '.colour' red
{"colour":"red","name":"Tom"}
```

If you have at least dasel `v1.11.0` you can use `dasel update` to get the latest version, otherwise you should download the latest executable from the latest release.

**Comment by tobiashochguertel** [comment]
Impressive! You managed this feature request so quickly and without hassle.
I ask me if this response time is a personal archivement or that golang is such a elegant Development environment which helps to resolve things in quick way.

Thanks 🙏🏻:)
