### ISSUE TITLE
Please release using `darwin` not `macos`

### ISSUE THREAD

**Issue by ghostsquad** [TomWright/dasel#83]
this is to enable scripts that use `uname` to detect the platform to know which binary to download.

**Comment by TomWright** [comment]
I can fix this going forward by updating the build scripts (see the linked pull request), however updating this historically could be a bit of a pain.

Do you need this fixed historically?

I dealt with this in the following way:

https://github.com/TomWright/dasel/blob/23a3cdd69ef8097e4a6e2dddb3e6c120aaff3db8/internal/selfupdate/release.go#L43-L62

You may need to do something similar to be able to find the darwin release across all versions.

**Comment by TomWright** [comment]
Fixed as of `v1.12.1`: https://github.com/TomWright/dasel/releases/tag/v1.12.1

There is still the issue of historical releases but I think that's a non-issue.

**Comment by ghostsquad** [comment]
I'll make a comment in asdf dasel in the readme about the pre 0.12 releases
