### ISSUE TITLE
Homebrew releases

### ISSUE THREAD

**Issue by TomWright** [TomWright/dasel#86]
It would be good to use [goreleaser](https://goreleaser.com/) for releases.

This will make it easy to add homebrew/linux package support.

**Comment by alebcay** [comment]
FYI (and somewhat tangential), but I've submitted `dasel` for inclusion in the Homebrew core repos in https://github.com/Homebrew/homebrew-core/pull/70488. If accepted, `dasel` will be available for installation on macOS and Linux with `brew install dasel`.

Generally, end users and Homebrew maintainers will notice upstream package releases and update the downstream package for distribution, but you could also, for instance, automate an update submission downstream to Homebrew with a GitHub action like [homebrew-bump-formula](https://github.com/marketplace/actions/homebrew-bump-formula).

**Comment by TomWright** [comment]
Thanks for letting me know, that's really useful. I'll check back in once the PR has had a reply.

**Comment by alebcay** [comment]
The downstream PR has been merged 💯.

**Comment by TomWright** [comment]
Thanks for that great contribution 💯.

I've updated the README here: https://github.com/TomWright/dasel#homebrew

I will implement the homebrew-bump-formula action before the next release.
