### ISSUE TITLE
Option to sort keys on output

### ISSUE THREAD

**Issue by varac** [TomWright/dasel#95]
**Is your feature request related to a problem? Please describe.**

I'd like to sort the output by keys, like `jq` can:

```
❯ jq --help | grep sort
  -S               sort keys of objects on output;
```

**Describe the solution you'd like**

A similar flag i.e. `-s` to sort keys.

**Comment by TomWright** [comment]
Which data format are you working with? I'm not eager to implement this as dasel doesn't have much (if any) control over the marshaling of data.

I believe JSON already does this by default... ["The map keys are sorted and used as JSON object keys"](https://golang.org/pkg/encoding/json/#Marshal).

**Comment by varac** [comment]
I could use this mainly for yaml

**Comment by TomWright** [comment]
This is the default behaviour for both JSON and YAML marshaling in golang, so is the default behaviour in dasel.

## YAML output
```bash
echo 'c: 1
b: 1
1: 1
2: 1
3: 1
5: 1
d: 1' | dasel -r yaml -w yaml .
```

```yaml
"1": 1
"2": 1
"3": 1
"5": 1
b: 1
c: 1
d: 1
```

## JSON output
## YAML output
```bash
echo 'c: 1
b: 1
1: 1
2: 1
3: 1
5: 1
d: 1' | dasel -r yaml -w json .
```

```json
{
  "1": 1,
  "2": 1,
  "3": 1,
  "5": 1,
  "b": 1,
  "c": 1,
  "d": 1
}

```
